//
// CreditInterest1TierBandSet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The group of tiers or bands for which credit interest can be applied. */

public struct CreditInterest1TierBandSet: Codable {

    public enum TierBandMethod: String, Codable { 
        case tiered = "Tiered"
        case whole = "Whole"
    }
    public enum CalculationMethod: String, Codable { 
        case compound = "Compound"
        case simpleInterest = "SimpleInterest"
    }
    public enum Destination: String, Codable { 
        case payAway = "PayAway"
        case selfCredit = "SelfCredit"
    }
    /** The methodology of how credit interest is charged. It can be:-  1. Banded Interest rates are banded. i.e. Increasing rate on whole balance as balance increases.  2. Tiered Interest rates are tiered. i.e. increasing rate for each tier as balance increases, but interest paid on tier fixed for that tier and not on whole balance.  3. Whole The same interest rate is applied irrespective of the PCA balance */
    public var tierBandMethod: TierBandMethod
    /** Methods of calculating interest */
    public var calculationMethod: CalculationMethod?
    /** Describes whether accrued interest is payable only to the PCA or to another bank account */
    public var destination: Destination?
    /** Optional additional notes to supplement the Tier Band Set details */
    public var notes: [String]?
    /** Tier Band Details */
    public var tierBand: [CreditInterest1TierBand]

    public init(tierBandMethod: TierBandMethod, calculationMethod: CalculationMethod?, destination: Destination?, notes: [String]?, tierBand: [CreditInterest1TierBand]) {
        self.tierBandMethod = tierBandMethod
        self.calculationMethod = calculationMethod
        self.destination = destination
        self.notes = notes
        self.tierBand = tierBand
    }

    public enum CodingKeys: String, CodingKey { 
        case tierBandMethod = "TierBandMethod"
        case calculationMethod = "CalculationMethod"
        case destination = "Destination"
        case notes = "Notes"
        case tierBand = "TierBand"
    }


}

