//
// OBDirectDebit1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Account to or from which a cash entry is made. */

public struct OBDirectDebit1: Codable {

    public var accountId: AccountId
    /** A unique and immutable identifier used to identify the direct debit resource. This identifier has no meaning to the account owner. */
    public var directDebitId: String?
    /** Direct Debit reference. For AUDDIS service users provide Core Reference. For non AUDDIS service users provide Core reference if possible or last used reference. */
    public var mandateIdentification: String
    public var directDebitStatusCode: OBExternalDirectDebitStatus1Code?
    /** Name of Service User. */
    public var name: String
    /** Date of most recent direct debit collection. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var previousPaymentDateTime: Date?
    public var previousPaymentAmount: OBActiveOrHistoricCurrencyAndAmount?

    public init(accountId: AccountId, directDebitId: String?, mandateIdentification: String, directDebitStatusCode: OBExternalDirectDebitStatus1Code?, name: String, previousPaymentDateTime: Date?, previousPaymentAmount: OBActiveOrHistoricCurrencyAndAmount?) {
        self.accountId = accountId
        self.directDebitId = directDebitId
        self.mandateIdentification = mandateIdentification
        self.directDebitStatusCode = directDebitStatusCode
        self.name = name
        self.previousPaymentDateTime = previousPaymentDateTime
        self.previousPaymentAmount = previousPaymentAmount
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "AccountId"
        case directDebitId = "DirectDebitId"
        case mandateIdentification = "MandateIdentification"
        case directDebitStatusCode = "DirectDebitStatusCode"
        case name = "Name"
        case previousPaymentDateTime = "PreviousPaymentDateTime"
        case previousPaymentAmount = "PreviousPaymentAmount"
    }


}

