//
// OBExternalCardSchemeType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Name of the card scheme. */
public enum OBExternalCardSchemeType1Code: String, Codable {
    case americanExpress = "AmericanExpress"
    case diners = "Diners"
    case discover = "Discover"
    case masterCard = "MasterCard"
    case visa = "VISA"

}
