//
// OBExternalStatementType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Statement type, in a coded form. */
public enum OBExternalStatementType1Code: String, Codable {
    case accountClosure = "AccountClosure"
    case accountOpening = "AccountOpening"
    case annual = "Annual"
    case interim = "Interim"
    case regularPeriodic = "RegularPeriodic"

}
