//
// OBExternalStatementInterestFrequency1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the statement fee type requested */

public struct OBExternalStatementInterestFrequency1Code: Codable {




}

