//
// OBFeeCategory1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Categorisation of fees and charges into standard categories. */
public enum OBFeeCategory1Code: String, Codable {
    case fcot = "FCOT"
    case fcre = "FCRE"
    case fcsv = "FCSV"

}
