//
// OBFeeType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Fee/charge type which is being capped */
public enum OBFeeType1Code: String, Codable {
    case fepf = "FEPF"
    case ftot = "FTOT"
    case fyaf = "FYAF"
    case fyam = "FYAM"
    case fyaq = "FYAQ"
    case fycp = "FYCP"
    case fydb = "FYDB"
    case fymi = "FYMI"
    case fyxx = "FYXX"

}
