//
// OBFrequency1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** How often is interest applied to the Product for this tier/band i.e. how often the financial institution pays accumulated interest to the customer&#39;s account. */
public enum OBFrequency1Code: String, Codable {
    case fqat = "FQAT"
    case fqdy = "FQDY"
    case fqhy = "FQHY"
    case fqmy = "FQMY"
    case fqot = "FQOT"
    case fqqy = "FQQY"
    case fqsd = "FQSD"
    case fqwy = "FQWY"
    case fqyy = "FQYY"

}
