//
// OBInterestCalculationMethod1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Methods of calculating interest */
public enum OBInterestCalculationMethod1Code: String, Codable {
    case itco = "ITCO"
    case itot = "ITOT"
    case itsi = "ITSI"

}
