//
// OBOverdraftTierBand1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Provides overdraft details for a specific tier or band */

public struct OBOverdraftTierBand1: Codable {

    /** Unique and unambiguous identification of a  Tier Band for a overdraft. */
    public var identification: String?
    /** Minimum value of Overdraft Tier/Band */
    public var tierValueMin: Double
    /** Minimum value of Overdraft Tier/Band */
    public var tierValueMax: Double?
    /** Minimum value of Overdraft Tier/Band */
    public var EAR: Double?
    /** Minimum value of Overdraft Tier/Band */
    public var agreementLengthMin: Double?
    /** Minimum value of Overdraft Tier/Band */
    public var agreementLengthMax: Double?
    public var agreementPeriod: OBPeriod1Code?
    public var overdraftInterestChargingCoverage: OBTierBandType1Code?
    /** Indicates whether the advertised overdraft rate is guaranteed to be offered to a borrower by the bank e.g. if it�s part of a government scheme, or whether the rate may vary dependent on the applicant�s circumstances. */
    public var bankGuaranteedIndicator: Bool?
    /** Optional additional notes to supplement the Tier/band details */
    public var notes: [String]?
    /** Overdraft fees and charges */
    public var overdraftFeesCharges: [OBOverdraftFeesCharges1]?

    public init(identification: String?, tierValueMin: Double, tierValueMax: Double?, EAR: Double?, agreementLengthMin: Double?, agreementLengthMax: Double?, agreementPeriod: OBPeriod1Code?, overdraftInterestChargingCoverage: OBTierBandType1Code?, bankGuaranteedIndicator: Bool?, notes: [String]?, overdraftFeesCharges: [OBOverdraftFeesCharges1]?) {
        self.identification = identification
        self.tierValueMin = tierValueMin
        self.tierValueMax = tierValueMax
        self.EAR = EAR
        self.agreementLengthMin = agreementLengthMin
        self.agreementLengthMax = agreementLengthMax
        self.agreementPeriod = agreementPeriod
        self.overdraftInterestChargingCoverage = overdraftInterestChargingCoverage
        self.bankGuaranteedIndicator = bankGuaranteedIndicator
        self.notes = notes
        self.overdraftFeesCharges = overdraftFeesCharges
    }

    public enum CodingKeys: String, CodingKey { 
        case identification = "Identification"
        case tierValueMin = "TierValueMin"
        case tierValueMax = "TierValueMax"
        case EAR
        case agreementLengthMin = "AgreementLengthMin"
        case agreementLengthMax = "AgreementLengthMax"
        case agreementPeriod = "AgreementPeriod"
        case overdraftInterestChargingCoverage = "OverdraftInterestChargingCoverage"
        case bankGuaranteedIndicator = "BankGuaranteedIndicator"
        case notes = "Notes"
        case overdraftFeesCharges = "OverdraftFeesCharges"
    }


}

