//
// OBPartyRelationships1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Party&#39;s relationships with other resources. */

public struct OBPartyRelationships1: Codable {

    public var account: OBRelationship1?

    public init(account: OBRelationship1?) {
        self.account = account
    }

    public enum CodingKeys: String, CodingKey { 
        case account = "Account"
    }


}

