//
// OBPeriod1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Period e.g. day, week, month etc. for which the fee/charge is capped */
public enum OBPeriod1Code: String, Codable {
    case pact = "PACT"
    case pday = "PDAY"
    case phyr = "PHYR"
    case pmth = "PMTH"
    case pqtr = "PQTR"
    case pwek = "PWEK"
    case pyer = "PYER"

}
