//
// OBReadDataProduct1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Aligning with the read write specs structure. */

public struct OBReadDataProduct1: Codable {

    /** Product details associated with the Account */
    public var product: [OBProduct1]?

    public init(product: [OBProduct1]?) {
        self.product = product
    }

    public enum CodingKeys: String, CodingKey { 
        case product = "Product"
    }


}

