//
// OBReadTransaction5Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadTransaction5Data: Codable {

    /** Provides further details on an entry in the report. */
    public var transaction: [OBTransaction5]?

    public init(transaction: [OBTransaction5]?) {
        self.transaction = transaction
    }

    public enum CodingKeys: String, CodingKey { 
        case transaction = "Transaction"
    }


}

