//
// OBReadStandingOrder5Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadStandingOrder5Data: Codable {

    public var standingOrder: [OBStandingOrder5]?

    public init(standingOrder: [OBStandingOrder5]?) {
        self.standingOrder = standingOrder
    }

    public enum CodingKeys: String, CodingKey { 
        case standingOrder = "StandingOrder"
    }


}

