//
// OBRepaymentFrequency1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Repayment frequency */
public enum OBRepaymentFrequency1Code: String, Codable {
    case smda = "SMDA"
    case smfl = "SMFL"
    case smfo = "SMFO"
    case smhy = "SMHY"
    case smmo = "SMMO"
    case smot = "SMOT"
    case smqu = "SMQU"
    case smwe = "SMWE"
    case smye = "SMYE"

}
