//
// OBTariffType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** TariffType which defines the fee and charges. */
public enum OBTariffType1Code: String, Codable {
    case ttel = "TTEL"
    case ttmx = "TTMX"
    case ttot = "TTOT"

}
