//
// OBTransactionCardInstrument1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements to describe the card instrument used in the transaction. */

public struct OBTransactionCardInstrument1: Codable {

    public var cardSchemeName: OBExternalCardSchemeType1Code
    public var authorisationType: OBExternalCardAuthorisationType1Code?
    /** Name of the cardholder using the card instrument. */
    public var name: String?
    /** Identification assigned by an institution to identify the card instrument used in the transaction. This identification is known by the account owner, and may be masked. */
    public var identification: String?

    public init(cardSchemeName: OBExternalCardSchemeType1Code, authorisationType: OBExternalCardAuthorisationType1Code?, name: String?, identification: String?) {
        self.cardSchemeName = cardSchemeName
        self.authorisationType = authorisationType
        self.name = name
        self.identification = identification
    }

    public enum CodingKeys: String, CodingKey { 
        case cardSchemeName = "CardSchemeName"
        case authorisationType = "AuthorisationType"
        case name = "Name"
        case identification = "Identification"
    }


}

