//
// OBActiveCurrencyAndAmountSimpleType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A number of monetary units specified in an active currency where the unit of currency is explicit and compliant with ISO 4217. */

//public struct OBActiveCurrencyAndAmountSimpleType: Codable {
//
//
//
//
//}

public typealias OBActiveCurrencyAndAmountSimpleType = String
