//
// OBCharge2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to provide details of a charge for the payment initiation. */

public struct OBCharge2: Codable {

    public var chargeBearer: OBChargeBearerType1Code
    public var type: OBExternalPaymentChargeType1Code
    public var amount: OBCharge2Amount

    public init(chargeBearer: OBChargeBearerType1Code, type: OBExternalPaymentChargeType1Code, amount: OBCharge2Amount) {
        self.chargeBearer = chargeBearer
        self.type = type
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey { 
        case chargeBearer = "ChargeBearer"
        case type = "Type"
        case amount = "Amount"
    }


}

