//
// OBDomestic2InstructedAmount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Amount of money to be moved between the debtor and creditor, before deduction of charges, expressed in the currency as ordered by the initiating party. Usage: This amount has to be transported unchanged through the transaction chain. */

public struct OBDomestic2InstructedAmount: Codable {

    public var amount: OBActiveCurrencyAndAmountSimpleType
    public var currency: String

    public init(amount: OBActiveCurrencyAndAmountSimpleType, currency: String) {
        self.amount = amount
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey { 
        case amount = "Amount"
        case currency = "Currency"
    }


}

