//
// OBDomesticStandingOrder3FinalPaymentAmount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The amount of the final Standing Order */

public struct OBDomesticStandingOrder3FinalPaymentAmount: Codable {

    public var amount: OBActiveCurrencyAndAmountSimpleType
    public var currency: String

    public init(amount: OBActiveCurrencyAndAmountSimpleType, currency: String) {
        self.amount = amount
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey { 
        case amount = "Amount"
        case currency = "Currency"
    }


}

