//
// OBExchangeRateType2Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the type used to complete the currency exchange. */
public enum OBExchangeRateType2Code: String, Codable {
    case actual = "Actual"
    case agreed = "Agreed"
    case indicative = "Indicative"

}
