//
// OBExternalPaymentContext1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the payment context */
public enum OBExternalPaymentContext1Code: String, Codable {
    case billPayment = "BillPayment"
    case ecommerceGoods = "EcommerceGoods"
    case ecommerceServices = "EcommerceServices"
    case other = "Other"
    case partyToParty = "PartyToParty"

}
