//
// OBExternalConsentStatus2Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the status of consent resource in code form. */
public enum OBExternalConsentStatus2Code: String, Codable {
    case authorised = "Authorised"
    case awaitingAuthorisation = "AwaitingAuthorisation"
    case awaitingUpload = "AwaitingUpload"
    case consumed = "Consumed"
    case rejected = "Rejected"

}
