//
// OBExternalPaymentChargeType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Charge type, in a coded form. */
//
//public struct OBExternalPaymentChargeType1Code: Codable {
//
//
//
//
//}
public typealias OBExternalPaymentChargeType1Code = String
