//
// OBExternalFileType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the payment file type. */

public struct OBExternalFileType1Code: Codable {




}

