//
// OBExternalStatus1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the status of resource in code form. */
public enum OBExternalStatus1Code: String, Codable {
    case initiationCompleted = "InitiationCompleted"
    case initiationFailed = "InitiationFailed"
    case initiationPending = "InitiationPending"

}
