//
// OBExternalConsentStatus1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the status of resource in code form. */
public enum OBExternalConsentStatus1Code: String, Codable {
    case authorised = "Authorised"
    case awaitingAuthorisation = "AwaitingAuthorisation"
    case consumed = "Consumed"
    case rejected = "Rejected"

}
