//
// OBFile2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Initiation payload is sent by the initiating party to the ASPSP. It is used to request movement of funds using a payment file. */

public struct OBFile2: Codable {

    public var fileType: OBExternalFileType1Code
    /** A base64 encoding of a SHA256 hash of the file to be uploaded. */
    public var fileHash: String
    /** Reference for the file. */
    public var fileReference: String?
    /** Number of individual transactions contained in the payment information group. */
    public var numberOfTransactions: String?
    /** Total of all individual amounts included in the group, irrespective of currencies. */
    public var controlSum: Double?
    /** Date at which the initiating party requests the clearing agent to process the payment.  Usage: This is the date on which the debtor&#39;s account is to be debited. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var requestedExecutionDateTime: Date?
    public var localInstrument: OBExternalLocalInstrument1Code?
    public var debtorAccount: OBCashAccountDebtor4?
    public var remittanceInformation: OBRemittanceInformation1?
    public var supplementaryData: OBSupplementaryData1?

    public init(fileType: OBExternalFileType1Code, fileHash: String, fileReference: String?, numberOfTransactions: String?, controlSum: Double?, requestedExecutionDateTime: Date?, localInstrument: OBExternalLocalInstrument1Code?, debtorAccount: OBCashAccountDebtor4?, remittanceInformation: OBRemittanceInformation1?, supplementaryData: OBSupplementaryData1?) {
        self.fileType = fileType
        self.fileHash = fileHash
        self.fileReference = fileReference
        self.numberOfTransactions = numberOfTransactions
        self.controlSum = controlSum
        self.requestedExecutionDateTime = requestedExecutionDateTime
        self.localInstrument = localInstrument
        self.debtorAccount = debtorAccount
        self.remittanceInformation = remittanceInformation
        self.supplementaryData = supplementaryData
    }

    public enum CodingKeys: String, CodingKey { 
        case fileType = "FileType"
        case fileHash = "FileHash"
        case fileReference = "FileReference"
        case numberOfTransactions = "NumberOfTransactions"
        case controlSum = "ControlSum"
        case requestedExecutionDateTime = "RequestedExecutionDateTime"
        case localInstrument = "LocalInstrument"
        case debtorAccount = "DebtorAccount"
        case remittanceInformation = "RemittanceInformation"
        case supplementaryData = "SupplementaryData"
    }


}

