//
// OBRisk1DeliveryAddress.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Information that locates and identifies a specific address, as defined by postal services or in free format text. */

public struct OBRisk1DeliveryAddress: Codable {

    /** Information that locates and identifies a specific address, as defined by postal services, that is presented in free format text. */
    public var addressLine: [String]?
    /** Name of a street or thoroughfare. */
    public var streetName: String?
    /** Number that identifies the position of a building on a street. */
    public var buildingNumber: String?
    /** Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail. */
    public var postCode: String?
    /** Name of a built-up area, with defined boundaries, and a local government. */
    public var townName: String
    /** Identifies a subdivision of a country, for instance state, region, county. */
    public var countrySubDivision: [String]?
    /** Nation with its own government, occupying a particular territory. */
    public var country: String

    public init(addressLine: [String]?, streetName: String?, buildingNumber: String?, postCode: String?, townName: String, countrySubDivision: [String]?, country: String) {
        self.addressLine = addressLine
        self.streetName = streetName
        self.buildingNumber = buildingNumber
        self.postCode = postCode
        self.townName = townName
        self.countrySubDivision = countrySubDivision
        self.country = country
    }

    public enum CodingKeys: String, CodingKey { 
        case addressLine = "AddressLine"
        case streetName = "StreetName"
        case buildingNumber = "BuildingNumber"
        case postCode = "PostCode"
        case townName = "TownName"
        case countrySubDivision = "CountrySubDivision"
        case country = "Country"
    }


}

