//
// CreditInterest1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the interest that may be payable to the PCA account holders */

public struct CreditInterest1: Codable {

    /** The group of tiers or bands for which credit interest can be applied. */
    public var tierBandSet: [CreditInterest1TierBandSet]

    public init(tierBandSet: [CreditInterest1TierBandSet]) {
        self.tierBandSet = tierBandSet
    }

    public enum CodingKeys: String, CodingKey { 
        case tierBandSet = "TierBandSet"
    }


}

