//
// CreditInterest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the interest that may be payable to the BCA account holders */

public struct CreditInterest: Codable {

    /** The group of tiers or bands for which credit interest can be applied. */
    public var tierBandSet: [CreditInterestTierBandSet]

    public init(tierBandSet: [CreditInterestTierBandSet]) {
        self.tierBandSet = tierBandSet
    }

    public enum CodingKeys: String, CodingKey { 
        case tierBandSet = "TierBandSet"
    }


}

