//
// OBCashBalance1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to define the balance details. */

public struct OBCashBalance1: Codable {

    public enum CreditDebitIndicator: String, Codable { 
        case credit = "Credit"
        case debit = "Debit"
    }
    public var accountId: AccountId
    /** Indicates whether the balance is a credit or a debit balance.  Usage: A zero balance is considered to be a credit balance. */
    public var creditDebitIndicator: CreditDebitIndicator
    public var type: OBBalanceType1Code
    /** Indicates the date (and time) of the balance. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var dateTime: Date
    public var amount: OBActiveOrHistoricCurrencyAndAmount
    /** Set of elements used to provide details on the credit line. */
    public var creditLine: [OBCreditLine1]?

    public init(accountId: AccountId, creditDebitIndicator: CreditDebitIndicator, type: OBBalanceType1Code, dateTime: Date, amount: OBActiveOrHistoricCurrencyAndAmount, creditLine: [OBCreditLine1]?) {
        self.accountId = accountId
        self.creditDebitIndicator = creditDebitIndicator
        self.type = type
        self.dateTime = dateTime
        self.amount = amount
        self.creditLine = creditLine
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "AccountId"
        case creditDebitIndicator = "CreditDebitIndicator"
        case type = "Type"
        case dateTime = "DateTime"
        case amount = "Amount"
        case creditLine = "CreditLine"
    }


}

