//
// OBCreditDebitCode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum OBCreditDebitCode: String, Codable {
    case credit = "Credit"
    case debit = "Debit"

}
