//
// OBEntryStatus1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Status of a transaction entry on the books of the account servicer. */
public enum OBEntryStatus1Code: String, Codable {
    case booked = "Booked"
    case pending = "Pending"

}
