//
// OBPCAData1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBPCAData1: Codable {

    public var productDetails: ProductDetails1?
    public var creditInterest: CreditInterest1?
    public var overdraft: Overdraft1?
    public var otherFeesCharges: OtherFeesCharges?

    public init(productDetails: ProductDetails1?, creditInterest: CreditInterest1?, overdraft: Overdraft1?, otherFeesCharges: OtherFeesCharges?) {
        self.productDetails = productDetails
        self.creditInterest = creditInterest
        self.overdraft = overdraft
        self.otherFeesCharges = otherFeesCharges
    }

    public enum CodingKeys: String, CodingKey { 
        case productDetails = "ProductDetails"
        case creditInterest = "CreditInterest"
        case overdraft = "Overdraft"
        case otherFeesCharges = "OtherFeesCharges"
    }


}

