//
// OBProduct2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBProduct2: Codable {

    /** The name of the product used for marketing purposes from a customer perspective. I.e. what the customer would recognise. */
    public var productName: String?
    /** Identifier within the parent organisation for the product. Must be unique in the organisation. */
    public var productId: String?
    public var accountId: AccountId
    /** Identifier within the parent organisation for the product. Must be unique in the organisation. */
    public var secondaryProductId: String?
    public var productType: OBExternalProductType1Code?
    /** Unique and unambiguous identification of a Product Marketing State. */
    public var marketingStateId: String?
    public var otherProductType: OBOtherProductType1?
    public var BCA: OBBCAData1?
    public var PCA: OBPCAData1?

    public init(productName: String?, productId: String?, accountId: AccountId, secondaryProductId: String?, productType: OBExternalProductType1Code?, marketingStateId: String?, otherProductType: OBOtherProductType1?, BCA: OBBCAData1?, PCA: OBPCAData1?) {
        self.productName = productName
        self.productId = productId
        self.accountId = accountId
        self.secondaryProductId = secondaryProductId
        self.productType = productType
        self.marketingStateId = marketingStateId
        self.otherProductType = otherProductType
        self.BCA = BCA
        self.PCA = PCA
    }

    public enum CodingKeys: String, CodingKey { 
        case productName = "ProductName"
        case productId = "ProductId"
        case accountId = "AccountId"
        case secondaryProductId = "SecondaryProductId"
        case productType = "ProductType"
        case marketingStateId = "MarketingStateId"
        case otherProductType = "OtherProductType"
        case BCA
        case PCA
    }


}

