//
// OBReadTransaction3Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadTransaction3Data: Codable {

    /** Provides further details on an entry in the report. */
    public var transaction: [OBTransaction3]?

    public init(transaction: [OBTransaction3]?) {
        self.transaction = transaction
    }

    public enum CodingKeys: String, CodingKey { 
        case transaction = "Transaction"
    }


}

