//
// OBReadBeneficiary2Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadBeneficiary2Data: Codable {

    public var beneficiary: [OBBeneficiary2]?

    public init(beneficiary: [OBBeneficiary2]?) {
        self.beneficiary = beneficiary
    }

    public enum CodingKeys: String, CodingKey { 
        case beneficiary = "Beneficiary"
    }


}

