//
// OBReadProduct2Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadProduct2Data: Codable {

    public var product: [OBProduct2]?

    public init(product: [OBProduct2]?) {
        self.product = product
    }

    public enum CodingKeys: String, CodingKey { 
        case product = "Product"
    }


}

