//
// OtherFeesCharges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains details of fees and charges which are not associated with either borrowing or features/benefits */

public struct OtherFeesCharges: Codable {

    /** Other fees/charges details */
    public var feeChargeDetail: [OtherFeesChargesFeeChargeDetail]
    /** Details about any caps (maximum charges) that apply to a particular fee/charge */
    public var feeChargeCap: [OtherFeesChargesFeeChargeCap]?

    public init(feeChargeDetail: [OtherFeesChargesFeeChargeDetail], feeChargeCap: [OtherFeesChargesFeeChargeCap]?) {
        self.feeChargeDetail = feeChargeDetail
        self.feeChargeCap = feeChargeCap
    }

    public enum CodingKeys: String, CodingKey { 
        case feeChargeDetail = "FeeChargeDetail"
        case feeChargeCap = "FeeChargeCap"
    }


}

