//
// BuildingNumber.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Number that identifies the position of a building on a street. */

public struct BuildingNumber: Codable {




}

