//
// Description1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Description that may be available for the statement fee. */

public struct Description1: Codable {




}

