//
// Identification1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Unique and unambiguous identification of the servicing institution. */

public struct Identification1: Codable {




}

