//
// Name2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Name by which an agent is known and which is usually used to identify that agent. */

public struct Name2: Codable {




}

