//
// OBAccountStatus1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the status of account resource in code form. */
public enum OBAccountStatus1Code: String, Codable {
    case deleted = "Deleted"
    case disabled = "Disabled"
    case enabled = "Enabled"
    case pending = "Pending"
    case proForma = "ProForma"

}
