//
// OBAmount14.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Cap amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate) */

public struct OBAmount14: Codable {




}

