//
// OBAmount12.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Amount charged for an overdraft fee/charge (where it is charged in terms of an amount rather than a rate) */

public struct OBAmount12: Codable {




}

