//
// OBAmount11.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Every additional tranche of an overdraft balance to which an overdraft fee is applied */

public struct OBAmount11: Codable {




}

