//
// OBBeneficiary3Basic.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBBeneficiary3Basic: Codable {

    public var accountId: AccountId?
    public var beneficiaryId: BeneficiaryId?
    public var reference: Reference?

    public init(accountId: AccountId?, beneficiaryId: BeneficiaryId?, reference: Reference?) {
        self.accountId = accountId
        self.beneficiaryId = beneficiaryId
        self.reference = reference
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "AccountId"
        case beneficiaryId = "BeneficiaryId"
        case reference = "Reference"
    }


}

