//
// OBBeneficiary3.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBBeneficiary3: Codable {

    public var accountId: AccountId?
    public var beneficiaryId: BeneficiaryId?
    public var reference: Reference?
    public var creditorAgent: OBBranchAndFinancialInstitutionIdentification62?
    public var creditorAccount: OBCashAccount51?

    public init(accountId: AccountId?, beneficiaryId: BeneficiaryId?, reference: Reference?, creditorAgent: OBBranchAndFinancialInstitutionIdentification62?, creditorAccount: OBCashAccount51?) {
        self.accountId = accountId
        self.beneficiaryId = beneficiaryId
        self.reference = reference
        self.creditorAgent = creditorAgent
        self.creditorAccount = creditorAccount
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "AccountId"
        case beneficiaryId = "BeneficiaryId"
        case reference = "Reference"
        case creditorAgent = "CreditorAgent"
        case creditorAccount = "CreditorAccount"
    }


}

