//
// OBCreditDebitCode1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Indicates whether the transaction is a credit or a debit entry. */
public enum OBCreditDebitCode1: String, Codable {
    case credit = "Credit"
    case debit = "Debit"

}
