//
// OBCreditDebitCode0.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Indicates whether the amount is a credit or a debit.  Usage: A zero amount is considered to be a credit amount. */
public enum OBCreditDebitCode0: String, Codable {
    case credit = "Credit"
    case debit = "Debit"

}
