//
// OBErrorResponse1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An array of detail error codes, and messages, and URLs to documentation to help remediation. */

public struct OBErrorResponse1: Codable {

    /** High level textual error code, to help categorize the errors. */
    public var code: String
    /** A unique reference for the error instance, for audit purposes, in case of unknown/unclassified errors. */
    public var _id: String?
    /** Brief Error message, e.g., &#39;There is something wrong with the request parameters provided&#39; */
    public var message: String
    public var errors: [OBError1]

    public init(code: String, _id: String?, message: String, errors: [OBError1]) {
        self.code = code
        self._id = _id
        self.message = message
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey { 
        case code = "Code"
        case _id = "Id"
        case message = "Message"
        case errors = "Errors"
    }


}

