//
// OBExternalStatementFeeRateType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Description that may be available for the statement fee rate type. */

public struct OBExternalStatementFeeRateType1Code: Codable {




}

