//
// OBInterestFixedVariableType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Type of interest rate, Fixed or Variable */
public enum OBInterestFixedVariableType1Code: String, Codable {
    case infi = "INFI"
    case inva = "INVA"

}
