//
// OBRate10.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Rate charged for overdraft fee/charge (where it is charged in terms of a rate rather than an amount) */

public struct OBRate10: Codable {




}

