//
// OBReadOffer1DataOffer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadOffer1DataOffer: Codable {

    public enum OfferType: String, Codable { 
        case balanceTransfer = "BalanceTransfer"
        case limitIncrease = "LimitIncrease"
        case moneyTransfer = "MoneyTransfer"
        case other = "Other"
        case promotionalRate = "PromotionalRate"
    }
    public var accountId: AccountId
    /** A unique and immutable identifier used to identify the offer resource. This identifier has no meaning to the account owner. */
    public var offerId: String?
    /** Offer type, in a coded form. */
    public var offerType: OfferType?
    /** Further details of the offer. */
    public var _description: String?
    /** Date and time at which the offer starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var startDateTime: Date?
    /** Date and time at which the offer ends.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var endDateTime: Date?
    /** Rate associated with the offer type. */
    public var rate: String?
    /** Value associated with the offer type. */
    public var value: Int?
    /** Further details of the term of the offer. */
    public var term: String?
    /** URL (Uniform Resource Locator) where documentation on the offer can be found */
    public var URL: String?
    public var amount: OBReadOffer1DataAmount?
    public var fee: OBReadOffer1DataFee?

    public init(accountId: AccountId, offerId: String?, offerType: OfferType?, _description: String?, startDateTime: Date?, endDateTime: Date?, rate: String?, value: Int?, term: String?, URL: String?, amount: OBReadOffer1DataAmount?, fee: OBReadOffer1DataFee?) {
        self.accountId = accountId
        self.offerId = offerId
        self.offerType = offerType
        self._description = _description
        self.startDateTime = startDateTime
        self.endDateTime = endDateTime
        self.rate = rate
        self.value = value
        self.term = term
        self.URL = URL
        self.amount = amount
        self.fee = fee
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "AccountId"
        case offerId = "OfferId"
        case offerType = "OfferType"
        case _description = "Description"
        case startDateTime = "StartDateTime"
        case endDateTime = "EndDateTime"
        case rate = "Rate"
        case value = "Value"
        case term = "Term"
        case URL
        case amount = "Amount"
        case fee = "Fee"
    }


}

