//
// OBReadDataTransaction5.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadDataTransaction5: Codable {

    public var transaction: [OBTransaction5]?

    public init(transaction: [OBTransaction5]?) {
        self.transaction = transaction
    }

    public enum CodingKeys: String, CodingKey { 
        case transaction = "Transaction"
    }


}

