//
// OBReadProduct2DataOtherProductTypeOtherFeesCharges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains details of fees and charges which are not associated with either Overdraft or features/benefits */

public struct OBReadProduct2DataOtherProductTypeOtherFeesCharges: Codable {

    public enum TariffType: String, Codable { 
        case ttel = "TTEL"
        case ttmx = "TTMX"
        case ttot = "TTOT"
    }
    /** TariffType which defines the fee and charges. */
    public var tariffType: TariffType?
    /** Name of the tariff */
    public var tariffName: String?
    public var otherTariffType: OBReadProduct2DataOtherProductTypeOtherTariffType?
    public var feeChargeDetail: [OBReadProduct2DataOtherProductTypeFeeChargeDetail]
    public var feeChargeCap: [OBReadProduct2DataOtherProductTypeFeeChargeCap]?

    public init(tariffType: TariffType?, tariffName: String?, otherTariffType: OBReadProduct2DataOtherProductTypeOtherTariffType?, feeChargeDetail: [OBReadProduct2DataOtherProductTypeFeeChargeDetail], feeChargeCap: [OBReadProduct2DataOtherProductTypeFeeChargeCap]?) {
        self.tariffType = tariffType
        self.tariffName = tariffName
        self.otherTariffType = otherTariffType
        self.feeChargeDetail = feeChargeDetail
        self.feeChargeCap = feeChargeCap
    }

    public enum CodingKeys: String, CodingKey { 
        case tariffType = "TariffType"
        case tariffName = "TariffName"
        case otherTariffType = "OtherTariffType"
        case feeChargeDetail = "FeeChargeDetail"
        case feeChargeCap = "FeeChargeCap"
    }


}

