//
// OBReadProduct2DataOtherProductTypeProductDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadProduct2DataOtherProductTypeProductDetails: Codable {

    public enum Segment: String, Codable { 
        case geas = "GEAS"
        case geba = "GEBA"
        case gebr = "GEBR"
        case gebu = "GEBU"
        case geci = "GECI"
        case gecs = "GECS"
        case gefb = "GEFB"
        case gefg = "GEFG"
        case geg = "GEG"
        case gegr = "GEGR"
        case gegs = "GEGS"
        case geot = "GEOT"
        case geov = "GEOV"
        case gepa = "GEPA"
        case gepr = "GEPR"
        case gere = "GERE"
        case gest = "GEST"
        case geya = "GEYA"
        case geyo = "GEYO"
        case psca = "PSCA"
        case pses = "PSES"
        case psnc = "PSNC"
        case psnp = "PSNP"
        case psrg = "PSRG"
        case psss = "PSSS"
        case psst = "PSST"
        case pssw = "PSSW"
    }
    public enum FeeFreeLengthPeriod: String, Codable { 
        case pact = "PACT"
        case pday = "PDAY"
        case phyr = "PHYR"
        case pmth = "PMTH"
        case pqtr = "PQTR"
        case pwek = "PWEK"
        case pyer = "PYER"
    }
    public var segment: [Segment]?
    /** The length/duration of the fee free period */
    public var feeFreeLength: Int?
    /** The unit of period (days, weeks, months etc.) of the promotional length */
    public var feeFreeLengthPeriod: FeeFreeLengthPeriod?
    /** The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order */
    public var monthlyMaximumCharge: String?
    public var notes: [String]?
    public var otherSegment: OBOtherCodeType10?

    public init(segment: [Segment]?, feeFreeLength: Int?, feeFreeLengthPeriod: FeeFreeLengthPeriod?, monthlyMaximumCharge: String?, notes: [String]?, otherSegment: OBOtherCodeType10?) {
        self.segment = segment
        self.feeFreeLength = feeFreeLength
        self.feeFreeLengthPeriod = feeFreeLengthPeriod
        self.monthlyMaximumCharge = monthlyMaximumCharge
        self.notes = notes
        self.otherSegment = otherSegment
    }

    public enum CodingKeys: String, CodingKey { 
        case segment = "Segment"
        case feeFreeLength = "FeeFreeLength"
        case feeFreeLengthPeriod = "FeeFreeLengthPeriod"
        case monthlyMaximumCharge = "MonthlyMaximumCharge"
        case notes = "Notes"
        case otherSegment = "OtherSegment"
    }


}

