//
// OBReadAccount4Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadAccount4Data: Codable {

    public var account: [OBAccount4]?

    public init(account: [OBAccount4]?) {
        self.account = account
    }

    public enum CodingKeys: String, CodingKey { 
        case account = "Account"
    }


}

