//
// OBReadProduct2DataOtherProductTypeOverdraftOverdraftFeesCharges1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Overdraft fees and charges details */

public struct OBReadProduct2DataOtherProductTypeOverdraftOverdraftFeesCharges1: Codable {

    public var overdraftFeeChargeCap: [OBReadProduct2DataOtherProductTypeOverdraftOverdraftFeeChargeCap]?
    public var overdraftFeeChargeDetail: [OBReadProduct2DataOtherProductTypeOverdraftOverdraftFeeChargeDetail]

    public init(overdraftFeeChargeCap: [OBReadProduct2DataOtherProductTypeOverdraftOverdraftFeeChargeCap]?, overdraftFeeChargeDetail: [OBReadProduct2DataOtherProductTypeOverdraftOverdraftFeeChargeDetail]) {
        self.overdraftFeeChargeCap = overdraftFeeChargeCap
        self.overdraftFeeChargeDetail = overdraftFeeChargeDetail
    }

    public enum CodingKeys: String, CodingKey { 
        case overdraftFeeChargeCap = "OverdraftFeeChargeCap"
        case overdraftFeeChargeDetail = "OverdraftFeeChargeDetail"
    }


}

