//
// OBStatement2StatementValue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to provide details of a generic number value related to the statement resource. */

public struct OBStatement2StatementValue: Codable {

    public var value: OBExternalStatementValueType1Code
    public var type: Type1

    public init(value: OBExternalStatementValueType1Code, type: Type1) {
        self.value = value
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case value = "Value"
        case type = "Type"
    }


}

