//
// OBSupplementaryData1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Additional information that can not be captured in the structured fields and/or any other specific block. */

public struct OBSupplementaryData1: Codable {




}

