//
// Overdraft1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about Overdraft rates, fees &amp; charges */

public struct Overdraft1: Codable {

    /** Associated Notes about the overdraft rates */
    public var notes: [String]?
    /** Tier band set details */
    public var overdraftTierBandSet: [Overdraft1OverdraftTierBandSet]

    public init(notes: [String]?, overdraftTierBandSet: [Overdraft1OverdraftTierBandSet]) {
        self.notes = notes
        self.overdraftTierBandSet = overdraftTierBandSet
    }

    public enum CodingKeys: String, CodingKey { 
        case notes = "Notes"
        case overdraftTierBandSet = "OverdraftTierBandSet"
    }


}

