//
// TownName.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Name of a built-up area, with defined boundaries, and a local government. */

public struct TownName: Codable {




}

