//
// TransactionReference.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Unique reference for the transaction. This reference is optionally populated, and may as an example be the FPID in the Faster Payments context. */

public struct TransactionReference: Codable {




}

