//
// Type0.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Statement rate type, in a coded form. */

public struct Type0: Codable {




}

