//
// CountrySubDivision.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Identifies a subdivision of a country such as state, region, county. */

public struct CountrySubDivision: Codable {




}

