//
// CountryCode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Nation with its own government. */

public struct CountryCode: Codable {




}

