//
// Department.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Identification of a division of a large organisation or building. */

public struct Department: Codable {




}

