//
// Identification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Identification assigned by an institution to identify an account. This identification is known by the account owner. */

//public struct Identification: Codable {
//
//
//
//
//}

public typealias Identification = String
