//
// OBChargeBearerType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies which party/parties will bear the charges associated with the processing of the payment transaction. */
public enum OBChargeBearerType1Code: String, Codable {
    case borneByCreditor = "BorneByCreditor"
    case borneByDebtor = "BorneByDebtor"
    case followingServiceLevel = "FollowingServiceLevel"
    case shared = "Shared"

}
