//
// OBExternalAccountIdentification4Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Name of the identification scheme, in a coded form as published in an external list. */

//public struct OBExternalAccountIdentification4Code: Codable {
//
//
//
//
//}

public typealias OBExternalAccountIdentification4Code = String
