//
// OBPostalAddress6.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Information that locates and identifies a specific address, as defined by postal services. */

public struct OBPostalAddress6: Codable {

    public var addressType: OBAddressTypeCode?
    public var department: Department?
    public var subDepartment: SubDepartment?
    public var streetName: StreetName?
    public var buildingNumber: BuildingNumber?
    public var postCode: PostCode?
    public var townName: TownName?
    public var countrySubDivision: CountrySubDivision?
    public var country: CountryCode?
    public var addressLine: [String]?

    public init(addressType: OBAddressTypeCode?, department: Department?, subDepartment: SubDepartment?, streetName: StreetName?, buildingNumber: BuildingNumber?, postCode: PostCode?, townName: TownName?, countrySubDivision: CountrySubDivision?, country: CountryCode?, addressLine: [String]?) {
        self.addressType = addressType
        self.department = department
        self.subDepartment = subDepartment
        self.streetName = streetName
        self.buildingNumber = buildingNumber
        self.postCode = postCode
        self.townName = townName
        self.countrySubDivision = countrySubDivision
        self.country = country
        self.addressLine = addressLine
    }

    public enum CodingKeys: String, CodingKey { 
        case addressType = "AddressType"
        case department = "Department"
        case subDepartment = "SubDepartment"
        case streetName = "StreetName"
        case buildingNumber = "BuildingNumber"
        case postCode = "PostCode"
        case townName = "TownName"
        case countrySubDivision = "CountrySubDivision"
        case country = "Country"
        case addressLine = "AddressLine"
    }


}

