//
// OBRisk1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Risk section is sent by the initiating party to the ASPSP. It is used to specify additional details for risk scoring for Payments. */

public struct OBRisk1: Codable {

    public enum PaymentContextCode: String, Codable { 
        case billPayment = "BillPayment"
        case ecommerceGoods = "EcommerceGoods"
        case ecommerceServices = "EcommerceServices"
        case other = "Other"
        case partyToParty = "PartyToParty"
    }
    /** Specifies the payment context */
    public var paymentContextCode: PaymentContextCode?
    /** Category code conform to ISO 18245, related to the type of services or goods the merchant provides for the transaction. */
    public var merchantCategoryCode: String?
    /** The unique customer identifier of the PSU with the merchant. */
    public var merchantCustomerIdentification: String?
    public var deliveryAddress: OBRisk1DeliveryAddress?

    public init(paymentContextCode: PaymentContextCode?, merchantCategoryCode: String?, merchantCustomerIdentification: String?, deliveryAddress: OBRisk1DeliveryAddress?) {
        self.paymentContextCode = paymentContextCode
        self.merchantCategoryCode = merchantCategoryCode
        self.merchantCustomerIdentification = merchantCustomerIdentification
        self.deliveryAddress = deliveryAddress
    }

    public enum CodingKeys: String, CodingKey { 
        case paymentContextCode = "PaymentContextCode"
        case merchantCategoryCode = "MerchantCategoryCode"
        case merchantCustomerIdentification = "MerchantCustomerIdentification"
        case deliveryAddress = "DeliveryAddress"
    }


}

