//
// OBWritePaymentDetailsResponse1Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBWritePaymentDetailsResponse1Data: Codable {

    public var paymentStatus: [OBWritePaymentDetailsResponse1DataPaymentStatus]?

    public init(paymentStatus: [OBWritePaymentDetailsResponse1DataPaymentStatus]?) {
        self.paymentStatus = paymentStatus
    }

    public enum CodingKeys: String, CodingKey { 
        case paymentStatus = "PaymentStatus"
    }


}

