//
// OBWriteInternational2DataInitiationCreditorAgent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Financial institution servicing an account for the creditor. */

public struct OBWriteInternational2DataInitiationCreditorAgent: Codable {

    /** Name of the identification scheme, in a coded form as published in an external list. */
    public var schemeName: String?
    /** Unique and unambiguous identification of a financial institution or a branch of a financial institution. */
    public var identification: String?
    /** Name by which an agent is known and which is usually used to identify that agent. */
    public var name: String?
    public var postalAddress: OBPostalAddress6?

    public init(schemeName: String?, identification: String?, name: String?, postalAddress: OBPostalAddress6?) {
        self.schemeName = schemeName
        self.identification = identification
        self.name = name
        self.postalAddress = postalAddress
    }

    public enum CodingKeys: String, CodingKey { 
        case schemeName = "SchemeName"
        case identification = "Identification"
        case name = "Name"
        case postalAddress = "PostalAddress"
    }


}

