//
// OBWriteDomestic2DataInitiationDebtorAccount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Unambiguous identification of the account of the debtor to which a debit entry will be made as a result of the transaction. */

public struct OBWriteDomestic2DataInitiationDebtorAccount: Codable {

    public var schemeName: OBExternalAccountIdentification4Code
    public var identification: Identification
    /** The account name is the name or names of the account owner(s) represented at an account level, as displayed by the ASPSP&#39;s online channels. Note, the account name is not the product name or the nickname of the account. */
    public var name: String?
    public var secondaryIdentification: SecondaryIdentification?

    public init(schemeName: OBExternalAccountIdentification4Code, identification: Identification, name: String?, secondaryIdentification: SecondaryIdentification?) {
        self.schemeName = schemeName
        self.identification = identification
        self.name = name
        self.secondaryIdentification = secondaryIdentification
    }

    public enum CodingKeys: String, CodingKey { 
        case schemeName = "SchemeName"
        case identification = "Identification"
        case name = "Name"
        case secondaryIdentification = "SecondaryIdentification"
    }


}

