//
// OBWritePaymentDetailsResponse1DataPaymentStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Payment status details. */

public struct OBWritePaymentDetailsResponse1DataPaymentStatus: Codable {

    public enum Status: String, Codable { 
        case accepted = "Accepted"
        case acceptedCancellationRequest = "AcceptedCancellationRequest"
        case acceptedCreditSettlementCompleted = "AcceptedCreditSettlementCompleted"
        case acceptedCustomerProfile = "AcceptedCustomerProfile"
        case acceptedFundsChecked = "AcceptedFundsChecked"
        case acceptedSettlementCompleted = "AcceptedSettlementCompleted"
        case acceptedSettlementInProcess = "AcceptedSettlementInProcess"
        case acceptedTechnicalValidation = "AcceptedTechnicalValidation"
        case acceptedWithChange = "AcceptedWithChange"
        case acceptedWithoutPosting = "AcceptedWithoutPosting"
        case cancelled = "Cancelled"
        case noCancellationProcess = "NoCancellationProcess"
        case partiallyAcceptedCancellationRequest = "PartiallyAcceptedCancellationRequest"
        case partiallyAcceptedTechnicalCorrect = "PartiallyAcceptedTechnicalCorrect"
        case paymentCancelled = "PaymentCancelled"
        case pending = "Pending"
        case pendingCancellationRequest = "PendingCancellationRequest"
        case received = "Received"
        case rejected = "Rejected"
        case rejectedCancellationRequest = "RejectedCancellationRequest"
    }
    /** Unique identifier for the transaction within an servicing institution. This identifier is both unique and immutable. */
    public var paymentTransactionId: String
    /** Status of a transfe, as assigned by the transaction administrator. */
    public var status: Status
    /** Date and time at which the status was assigned to the transfer.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var statusUpdateDateTime: Date
    public var statusDetail: OBWritePaymentDetailsResponse1DataStatusDetail?

    public init(paymentTransactionId: String, status: Status, statusUpdateDateTime: Date, statusDetail: OBWritePaymentDetailsResponse1DataStatusDetail?) {
        self.paymentTransactionId = paymentTransactionId
        self.status = status
        self.statusUpdateDateTime = statusUpdateDateTime
        self.statusDetail = statusDetail
    }

    public enum CodingKeys: String, CodingKey { 
        case paymentTransactionId = "PaymentTransactionId"
        case status = "Status"
        case statusUpdateDateTime = "StatusUpdateDateTime"
        case statusDetail = "StatusDetail"
    }


}

