//
// OBWritePaymentDetailsResponse1DataStatusDetail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Payment status details as per underlying Payment Rail. */

public struct OBWritePaymentDetailsResponse1DataStatusDetail: Codable {

    public enum StatusReason: String, Codable { 
        case cancelled = "Cancelled"
        case pendingFailingSettlement = "PendingFailingSettlement"
        case pendingSettlement = "PendingSettlement"
        case proprietary = "Proprietary"
        case proprietaryRejection = "ProprietaryRejection"
        case suspended = "Suspended"
        case unmatched = "Unmatched"
    }
    public var localInstrument: OBExternalLocalInstrument1Code?
    /** Status of a transfer, as assigned by the transaction administrator. */
    public var status: String
    /** Reason Code provided for the status of a transfer. */
    public var statusReason: StatusReason?
    /** Reason provided for the status of a transfer. */
    public var statusReasonDescription: String?

    public init(localInstrument: OBExternalLocalInstrument1Code?, status: String, statusReason: StatusReason?, statusReasonDescription: String?) {
        self.localInstrument = localInstrument
        self.status = status
        self.statusReason = statusReason
        self.statusReasonDescription = statusReasonDescription
    }

    public enum CodingKeys: String, CodingKey { 
        case localInstrument = "LocalInstrument"
        case status = "Status"
        case statusReason = "StatusReason"
        case statusReasonDescription = "StatusReasonDescription"
    }


}

