//
// OBWriteInternationalStandingOrderResponse4Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBWriteInternationalStandingOrderResponse4Data: Codable {

    public enum Status: String, Codable { 
        case cancelled = "Cancelled"
        case initiationCompleted = "InitiationCompleted"
        case initiationFailed = "InitiationFailed"
        case initiationPending = "InitiationPending"
    }
    /** OB: Unique identification as assigned by the ASPSP to uniquely identify the international standing order resource. */
    public var internationalStandingOrderId: String
    /** OB: Unique identification as assigned by the ASPSP to uniquely identify the consent resource. */
    public var consentId: String
    /** Date and time at which the resource was created.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var creationDateTime: Date
    /** Specifies the status of resource in code form. */
    public var status: Status
    /** Date and time at which the resource status was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var statusUpdateDateTime: Date
    public var charges: [OBWriteDomesticConsentResponse3DataCharges]?
    public var initiation: OBWriteInternationalStandingOrder3DataInitiation
    public var multiAuthorisation: OBWriteDomesticResponse3DataMultiAuthorisation?

    public init(internationalStandingOrderId: String, consentId: String, creationDateTime: Date, status: Status, statusUpdateDateTime: Date, charges: [OBWriteDomesticConsentResponse3DataCharges]?, initiation: OBWriteInternationalStandingOrder3DataInitiation, multiAuthorisation: OBWriteDomesticResponse3DataMultiAuthorisation?) {
        self.internationalStandingOrderId = internationalStandingOrderId
        self.consentId = consentId
        self.creationDateTime = creationDateTime
        self.status = status
        self.statusUpdateDateTime = statusUpdateDateTime
        self.charges = charges
        self.initiation = initiation
        self.multiAuthorisation = multiAuthorisation
    }

    public enum CodingKeys: String, CodingKey { 
        case internationalStandingOrderId = "InternationalStandingOrderId"
        case consentId = "ConsentId"
        case creationDateTime = "CreationDateTime"
        case status = "Status"
        case statusUpdateDateTime = "StatusUpdateDateTime"
        case charges = "Charges"
        case initiation = "Initiation"
        case multiAuthorisation = "MultiAuthorisation"
    }


}

