//
// OBWriteInternationalScheduled2Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBWriteInternationalScheduled2Data: Codable {

    /** OB: Unique identification as assigned by the ASPSP to uniquely identify the consent resource. */
    public var consentId: String
    public var initiation: OBWriteInternationalScheduled2DataInitiation

    public init(consentId: String, initiation: OBWriteInternationalScheduled2DataInitiation) {
        self.consentId = consentId
        self.initiation = initiation
    }

    public enum CodingKeys: String, CodingKey { 
        case consentId = "ConsentId"
        case initiation = "Initiation"
    }


}

