//
// OBWriteDomesticConsent3DataSCASupportData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Supporting Data provided by TPP, when requesting SCA Exemption. */

public struct OBWriteDomesticConsent3DataSCASupportData: Codable {

    public enum RequestedSCAExemptionType: String, Codable { 
        case billPayment = "BillPayment"
        case contactlessTravel = "ContactlessTravel"
        case ecommerceGoods = "EcommerceGoods"
        case ecommerceServices = "EcommerceServices"
        case kiosk = "Kiosk"
        case parking = "Parking"
        case partyToParty = "PartyToParty"
    }
    public enum AppliedAuthenticationApproach: String, Codable { 
        case ca = "CA"
        case sca = "SCA"
    }
    /** This field allows a PISP to request specific SCA Exemption for a Payment Initiation */
    public var requestedSCAExemptionType: RequestedSCAExemptionType?
    /** Specifies a character string with a maximum length of 40 characters. Usage: This field indicates whether the PSU was subject to SCA performed by the TPP */
    public var appliedAuthenticationApproach: AppliedAuthenticationApproach?
    /** Specifies a character string with a maximum length of 140 characters. Usage: If the payment is recurring then the transaction identifier of the previous payment occurrence so that the ASPSP can verify that the PISP, amount and the payee are the same as the previous occurrence. */
    public var referencePaymentOrderId: String?

    public init(requestedSCAExemptionType: RequestedSCAExemptionType?, appliedAuthenticationApproach: AppliedAuthenticationApproach?, referencePaymentOrderId: String?) {
        self.requestedSCAExemptionType = requestedSCAExemptionType
        self.appliedAuthenticationApproach = appliedAuthenticationApproach
        self.referencePaymentOrderId = referencePaymentOrderId
    }

    public enum CodingKeys: String, CodingKey { 
        case requestedSCAExemptionType = "RequestedSCAExemptionType"
        case appliedAuthenticationApproach = "AppliedAuthenticationApproach"
        case referencePaymentOrderId = "ReferencePaymentOrderId"
    }


}

