//
// OBWriteDomesticConsentResponse3Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBWriteDomesticConsentResponse3Data: Codable {

    public enum Status: String, Codable { 
        case authorised = "Authorised"
        case awaitingAuthorisation = "AwaitingAuthorisation"
        case consumed = "Consumed"
        case rejected = "Rejected"
    }
    /** OB: Unique identification as assigned by the ASPSP to uniquely identify the consent resource. */
    public var consentId: String
    /** Date and time at which the resource was created.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var creationDateTime: Date
    /** Specifies the status of consent resource in code form. */
    public var status: Status
    /** Date and time at which the resource status was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var statusUpdateDateTime: Date
    /** Specified cut-off date and time for the payment consent.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var cutOffDateTime: Date?
    /** Expected execution date and time for the payment resource.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var expectedExecutionDateTime: Date?
    /** Expected settlement date and time for the payment resource.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var expectedSettlementDateTime: Date?
    public var charges: [OBWriteDomesticConsentResponse3DataCharges]?
    public var initiation: OBWriteDomestic2DataInitiation
    public var authorisation: OBWriteDomesticConsent3DataAuthorisation?
    public var sCASupportData: OBWriteDomesticConsent3DataSCASupportData?

    public init(consentId: String, creationDateTime: Date, status: Status, statusUpdateDateTime: Date, cutOffDateTime: Date?, expectedExecutionDateTime: Date?, expectedSettlementDateTime: Date?, charges: [OBWriteDomesticConsentResponse3DataCharges]?, initiation: OBWriteDomestic2DataInitiation, authorisation: OBWriteDomesticConsent3DataAuthorisation?, sCASupportData: OBWriteDomesticConsent3DataSCASupportData?) {
        self.consentId = consentId
        self.creationDateTime = creationDateTime
        self.status = status
        self.statusUpdateDateTime = statusUpdateDateTime
        self.cutOffDateTime = cutOffDateTime
        self.expectedExecutionDateTime = expectedExecutionDateTime
        self.expectedSettlementDateTime = expectedSettlementDateTime
        self.charges = charges
        self.initiation = initiation
        self.authorisation = authorisation
        self.sCASupportData = sCASupportData
    }

    public enum CodingKeys: String, CodingKey { 
        case consentId = "ConsentId"
        case creationDateTime = "CreationDateTime"
        case status = "Status"
        case statusUpdateDateTime = "StatusUpdateDateTime"
        case cutOffDateTime = "CutOffDateTime"
        case expectedExecutionDateTime = "ExpectedExecutionDateTime"
        case expectedSettlementDateTime = "ExpectedSettlementDateTime"
        case charges = "Charges"
        case initiation = "Initiation"
        case authorisation = "Authorisation"
        case sCASupportData = "SCASupportData"
    }


}

