//
// OBWriteInternationalResponse3Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBWriteInternationalResponse3Data: Codable {

    public enum Status: String, Codable { 
        case acceptedCreditSettlementCompleted = "AcceptedCreditSettlementCompleted"
        case acceptedSettlementCompleted = "AcceptedSettlementCompleted"
        case acceptedSettlementInProcess = "AcceptedSettlementInProcess"
        case acceptedWithoutPosting = "AcceptedWithoutPosting"
        case pending = "Pending"
        case rejected = "Rejected"
    }
    /** OB: Unique identification as assigned by the ASPSP to uniquely identify the international payment resource. */
    public var internationalPaymentId: String
    /** OB: Unique identification as assigned by the ASPSP to uniquely identify the consent resource. */
    public var consentId: String
    /** Date and time at which the message was created.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var creationDateTime: Date
    /** Specifies the status of the payment information group. */
    public var status: Status
    /** Date and time at which the resource status was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var statusUpdateDateTime: Date
    /** Expected execution date and time for the payment resource.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var expectedExecutionDateTime: Date?
    /** Expected settlement date and time for the payment resource.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var expectedSettlementDateTime: Date?
    public var charges: [OBWriteDomesticConsentResponse3DataCharges]?
    public var exchangeRateInformation: OBWriteInternationalConsentResponse3DataExchangeRateInformation?
    public var initiation: OBWriteInternational2DataInitiation
    public var multiAuthorisation: OBWriteDomesticResponse3DataMultiAuthorisation?

    public init(internationalPaymentId: String, consentId: String, creationDateTime: Date, status: Status, statusUpdateDateTime: Date, expectedExecutionDateTime: Date?, expectedSettlementDateTime: Date?, charges: [OBWriteDomesticConsentResponse3DataCharges]?, exchangeRateInformation: OBWriteInternationalConsentResponse3DataExchangeRateInformation?, initiation: OBWriteInternational2DataInitiation, multiAuthorisation: OBWriteDomesticResponse3DataMultiAuthorisation?) {
        self.internationalPaymentId = internationalPaymentId
        self.consentId = consentId
        self.creationDateTime = creationDateTime
        self.status = status
        self.statusUpdateDateTime = statusUpdateDateTime
        self.expectedExecutionDateTime = expectedExecutionDateTime
        self.expectedSettlementDateTime = expectedSettlementDateTime
        self.charges = charges
        self.exchangeRateInformation = exchangeRateInformation
        self.initiation = initiation
        self.multiAuthorisation = multiAuthorisation
    }

    public enum CodingKeys: String, CodingKey { 
        case internationalPaymentId = "InternationalPaymentId"
        case consentId = "ConsentId"
        case creationDateTime = "CreationDateTime"
        case status = "Status"
        case statusUpdateDateTime = "StatusUpdateDateTime"
        case expectedExecutionDateTime = "ExpectedExecutionDateTime"
        case expectedSettlementDateTime = "ExpectedSettlementDateTime"
        case charges = "Charges"
        case exchangeRateInformation = "ExchangeRateInformation"
        case initiation = "Initiation"
        case multiAuthorisation = "MultiAuthorisation"
    }


}

