//
// OBWriteFile2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBWriteFile2: Codable {

    public var data: OBWriteFile2Data

    public init(data: OBWriteFile2Data) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case data = "Data"
    }


}

