//
// OBWriteFundsConfirmationResponse1DataFundsAvailableResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Result of a funds availability check. */

public struct OBWriteFundsConfirmationResponse1DataFundsAvailableResult: Codable {

    /** Date and time at which the funds availability check was generated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var fundsAvailableDateTime: Date
    /** Flag to indicate the availability of funds given the Amount in the consent request. */
    public var fundsAvailable: Bool

    public init(fundsAvailableDateTime: Date, fundsAvailable: Bool) {
        self.fundsAvailableDateTime = fundsAvailableDateTime
        self.fundsAvailable = fundsAvailable
    }

    public enum CodingKeys: String, CodingKey { 
        case fundsAvailableDateTime = "FundsAvailableDateTime"
        case fundsAvailable = "FundsAvailable"
    }


}

