//
// OBWriteFundsConfirmationResponse1Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBWriteFundsConfirmationResponse1Data: Codable {

    public var fundsAvailableResult: OBWriteFundsConfirmationResponse1DataFundsAvailableResult?
    public var supplementaryData: OBSupplementaryData1?

    public init(fundsAvailableResult: OBWriteFundsConfirmationResponse1DataFundsAvailableResult?, supplementaryData: OBSupplementaryData1?) {
        self.fundsAvailableResult = fundsAvailableResult
        self.supplementaryData = supplementaryData
    }

    public enum CodingKeys: String, CodingKey { 
        case fundsAvailableResult = "FundsAvailableResult"
        case supplementaryData = "SupplementaryData"
    }


}

