//
// OBWriteFileResponse2Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBWriteFileResponse2Data: Codable {

    public enum Status: String, Codable { 
        case initiationCompleted = "InitiationCompleted"
        case initiationFailed = "InitiationFailed"
        case initiationPending = "InitiationPending"
    }
    /** OB: Unique identification as assigned by the ASPSP to uniquely identify the file payment resource. */
    public var filePaymentId: String
    /** OB: Unique identification as assigned by the ASPSP to uniquely identify the consent resource. */
    public var consentId: String
    /** Date and time at which the message was created.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var creationDateTime: Date
    /** Specifies the status of the payment order resource. */
    public var status: Status
    /** Date and time at which the resource status was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var statusUpdateDateTime: Date
    public var charges: [OBWriteDomesticConsentResponse3DataCharges]?
    public var initiation: OBWriteFile2DataInitiation
    public var multiAuthorisation: OBWriteDomesticResponse3DataMultiAuthorisation?

    public init(filePaymentId: String, consentId: String, creationDateTime: Date, status: Status, statusUpdateDateTime: Date, charges: [OBWriteDomesticConsentResponse3DataCharges]?, initiation: OBWriteFile2DataInitiation, multiAuthorisation: OBWriteDomesticResponse3DataMultiAuthorisation?) {
        self.filePaymentId = filePaymentId
        self.consentId = consentId
        self.creationDateTime = creationDateTime
        self.status = status
        self.statusUpdateDateTime = statusUpdateDateTime
        self.charges = charges
        self.initiation = initiation
        self.multiAuthorisation = multiAuthorisation
    }

    public enum CodingKeys: String, CodingKey { 
        case filePaymentId = "FilePaymentId"
        case consentId = "ConsentId"
        case creationDateTime = "CreationDateTime"
        case status = "Status"
        case statusUpdateDateTime = "StatusUpdateDateTime"
        case charges = "Charges"
        case initiation = "Initiation"
        case multiAuthorisation = "MultiAuthorisation"
    }


}

