//
// PostCode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail. */

//public struct PostCode: Codable {
//
//
//
//
//}

public typealias PostCode = String

