//
// StreetName.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Name of a street or thoroughfare. */

//public struct StreetName: Codable {
//
//
//
//
//}

public typealias StreetName = String
