//
// FeeApplicableRange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Range or amounts or rates for which the fee/charge applies */

public struct FeeApplicableRange: Codable {

    /** Minimum Amount on which fee/charge is applicable (where it is expressed as an amount) */
    public var minimumAmount: String?
    /** Maximum Amount on which fee is applicable (where it is expressed as an amount) */
    public var maximumAmount: String?
    /** Minimum rate on which fee/charge is applicable(where it is expressed as an rate) */
    public var minimumRate: String?
    /** Maximum rate on which fee/charge is applicable(where it is expressed as an rate) */
    public var maximumRate: String?

    public init(minimumAmount: String?, maximumAmount: String?, minimumRate: String?, maximumRate: String?) {
        self.minimumAmount = minimumAmount
        self.maximumAmount = maximumAmount
        self.minimumRate = minimumRate
        self.maximumRate = maximumRate
    }

    public enum CodingKeys: String, CodingKey { 
        case minimumAmount = "MinimumAmount"
        case maximumAmount = "MaximumAmount"
        case minimumRate = "MinimumRate"
        case maximumRate = "MaximumRate"
    }


}

