//
// OBExternalAccountRole1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A party’s role with respect to the related account. */

public struct OBExternalAccountRole1Code: Codable {




}

