//
// OBExternalLegalStructureType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Legal standing of the party. */

public struct OBExternalLegalStructureType1Code: Codable {




}

