//
// OBExternalProductType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Product type : Personal Current Account, Business Current Account */
public enum OBExternalProductType1Code: String, Codable {
    case businessCurrentAccount = "BusinessCurrentAccount"
    case commercialCreditCard = "CommercialCreditCard"
    case other = "Other"
    case personalCurrentAccount = "PersonalCurrentAccount"
    case smeloan = "SMELoan"

}
