//
// OBExternalAccountType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the type of account (personal or business). */
public enum OBExternalAccountType1Code: String, Codable {
    case business = "Business"
    case personal = "Personal"

}
