//
// OBFeeChargeCap1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about any caps (maximum charges) that apply to a particular or group of fee/charge */

public struct OBFeeChargeCap1: Codable {

    /** Fee/charge type which is being capped */
    public var feeType: [OBFeeType1Code]
    public var minMaxType: OBMinMaxType1Code
    /** fee/charges are captured dependent on the number of occurrences rather than capped at a particular amount */
    public var feeCapOccurrence: Int?
    /** fee/charges are captured dependent on the number of occurrences rather than capped at a particular amount */
    public var feeCapAmount: Int?
    public var cappingPeriod: OBPeriod1Code?
    /** Free text for adding  extra details for fee charge cap */
    public var notes: [String]?
    /** Other fee type code which is not available in the standard code set */
    public var otherFeeType: [OBOtherCodeType1]?

    public init(feeType: [OBFeeType1Code], minMaxType: OBMinMaxType1Code, feeCapOccurrence: Int?, feeCapAmount: Int?, cappingPeriod: OBPeriod1Code?, notes: [String]?, otherFeeType: [OBOtherCodeType1]?) {
        self.feeType = feeType
        self.minMaxType = minMaxType
        self.feeCapOccurrence = feeCapOccurrence
        self.feeCapAmount = feeCapAmount
        self.cappingPeriod = cappingPeriod
        self.notes = notes
        self.otherFeeType = otherFeeType
    }

    public enum CodingKeys: String, CodingKey { 
        case feeType = "FeeType"
        case minMaxType = "MinMaxType"
        case feeCapOccurrence = "FeeCapOccurrence"
        case feeCapAmount = "FeeCapAmount"
        case cappingPeriod = "CappingPeriod"
        case notes = "Notes"
        case otherFeeType = "OtherFeeType"
    }


}

