//
// OBInterestDestination1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Describes whether accrued interest is payable only to the BCA or to another bank account */
public enum OBInterestDestination1Code: String, Codable {
    case inot = "INOT"
    case inpa = "INPA"
    case insc = "INSC"

}
