//
// OBLoanInterestTierBand1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Tier Band Details */

public struct OBLoanInterestTierBand1: Codable {

    /** Unique and unambiguous identification of a  Tier Band for a SME Loan. */
    public var identification: String?
    /** Minimum loan value for which the loan interest tier applies. */
    public var tierValueMinimum: Double
    /** Minimum loan value for which the loan interest tier applies. */
    public var tierValueMaximum: Double?
    /** Minimum loan value for which the loan interest tier applies. */
    public var tierValueMinTerm: Double
    public var minTermPeriod: OBPeriod1Code
    /** Minimum loan value for which the loan interest tier applies. */
    public var tierValueMaxTerm: Double?
    public var maxTermPeriod: OBPeriod1Code?
    public var fixedVariableInterestRateType: OBInterestFixedVariableType1Code
    /** Minimum loan value for which the loan interest tier applies. */
    public var repAPR: Double
    public var loanProviderInterestRateType: OBInterestRateType1Code?
    /** Minimum loan value for which the loan interest tier applies. */
    public var loanProviderInterestRate: Double?
    /** Optional additional notes to supplement the Tier Band details */
    public var notes: [String]?
    public var otherLoanProviderInterestRateType: OBOtherCodeType1?
    /** Contains details of fees and charges which are not associated with either LoanRepayment or features/benefits */
    public var loanInterestFeesCharges: [OBLoanInterestFeesCharges1]?

    public init(identification: String?, tierValueMinimum: Double, tierValueMaximum: Double?, tierValueMinTerm: Double, minTermPeriod: OBPeriod1Code, tierValueMaxTerm: Double?, maxTermPeriod: OBPeriod1Code?, fixedVariableInterestRateType: OBInterestFixedVariableType1Code, repAPR: Double, loanProviderInterestRateType: OBInterestRateType1Code?, loanProviderInterestRate: Double?, notes: [String]?, otherLoanProviderInterestRateType: OBOtherCodeType1?, loanInterestFeesCharges: [OBLoanInterestFeesCharges1]?) {
        self.identification = identification
        self.tierValueMinimum = tierValueMinimum
        self.tierValueMaximum = tierValueMaximum
        self.tierValueMinTerm = tierValueMinTerm
        self.minTermPeriod = minTermPeriod
        self.tierValueMaxTerm = tierValueMaxTerm
        self.maxTermPeriod = maxTermPeriod
        self.fixedVariableInterestRateType = fixedVariableInterestRateType
        self.repAPR = repAPR
        self.loanProviderInterestRateType = loanProviderInterestRateType
        self.loanProviderInterestRate = loanProviderInterestRate
        self.notes = notes
        self.otherLoanProviderInterestRateType = otherLoanProviderInterestRateType
        self.loanInterestFeesCharges = loanInterestFeesCharges
    }

    public enum CodingKeys: String, CodingKey { 
        case identification = "Identification"
        case tierValueMinimum = "TierValueMinimum"
        case tierValueMaximum = "TierValueMaximum"
        case tierValueMinTerm = "TierValueMinTerm"
        case minTermPeriod = "MinTermPeriod"
        case tierValueMaxTerm = "TierValueMaxTerm"
        case maxTermPeriod = "MaxTermPeriod"
        case fixedVariableInterestRateType = "FixedVariableInterestRateType"
        case repAPR = "RepAPR"
        case loanProviderInterestRateType = "LoanProviderInterestRateType"
        case loanProviderInterestRate = "LoanProviderInterestRate"
        case notes = "Notes"
        case otherLoanProviderInterestRateType = "OtherLoanProviderInterestRateType"
        case loanInterestFeesCharges = "LoanInterestFeesCharges"
    }


}

