//
// OBOtherProductDetails1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBOtherProductDetails1: Codable {

    /** Market segmentation is a marketing term referring to the aggregating of prospective buyers into groups, or segments, that have common needs and respond similarly to a marketing action. Market segmentation enables companies to target different categories of consumers who perceive the full value of certain products and services differently from one another. Read more: Market Segmentation http://www.investopedia.com/terms/m/marketsegmentation.asp#ixzz4gfEEalTd  */
    public var segment: [OBOtherProductSegment1Code]?
    /** The length/duration of the fee free period */
    public var feeFreeLength: Int?
    public var feeFreeLengthPeriod: OBPeriod1Code?
    /** The length/duration of the fee free period */
    public var monthlyMaximumCharge: Int?
    /** Optional additional notes to supplement the Core product details */
    public var notes: [String]?
    public var otherSegment: OBOtherCodeType1?

    public init(segment: [OBOtherProductSegment1Code]?, feeFreeLength: Int?, feeFreeLengthPeriod: OBPeriod1Code?, monthlyMaximumCharge: Int?, notes: [String]?, otherSegment: OBOtherCodeType1?) {
        self.segment = segment
        self.feeFreeLength = feeFreeLength
        self.feeFreeLengthPeriod = feeFreeLengthPeriod
        self.monthlyMaximumCharge = monthlyMaximumCharge
        self.notes = notes
        self.otherSegment = otherSegment
    }

    public enum CodingKeys: String, CodingKey { 
        case segment = "Segment"
        case feeFreeLength = "FeeFreeLength"
        case feeFreeLengthPeriod = "FeeFreeLengthPeriod"
        case monthlyMaximumCharge = "MonthlyMaximumCharge"
        case notes = "Notes"
        case otherSegment = "OtherSegment"
    }


}

