//
// OBOtherFeeChargeDetailType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Other Fee/charge type which is not available in the standard code set */

public struct OBOtherFeeChargeDetailType: Codable {

    /** The four letter Mnemonic used within an XML file to identify a code */
    public var code: String?
    public var feeCategory: OBFeeCategory1Code
    /** Long name associated with the code */
    public var name: String
    /** Description to describe the purpose of the code */
    public var _description: String

    public init(code: String?, feeCategory: OBFeeCategory1Code, name: String, _description: String) {
        self.code = code
        self.feeCategory = feeCategory
        self.name = name
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case code = "Code"
        case feeCategory = "FeeCategory"
        case name = "Name"
        case _description = "Description"
    }


}

