//
// OBOtherProductSegment1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Market segmentation is a marketing term referring to the aggregating of prospective buyers into groups, or segments, that have common needs and respond similarly to a marketing action. Market segmentation enables companies to target different categories of consumers who perceive the full value of certain products and services differently from one another. Read more: Market Segmentation http://www.investopedia.com/terms/m/marketsegmentation.asp#ixzz4gfEEalTd  */
public enum OBOtherProductSegment1Code: String, Codable {
    case geas = "GEAS"
    case geba = "GEBA"
    case gebr = "GEBR"
    case gebu = "GEBU"
    case geci = "GECI"
    case gecs = "GECS"
    case gefb = "GEFB"
    case gefg = "GEFG"
    case geg = "GEG"
    case gegr = "GEGR"
    case gegs = "GEGS"
    case geot = "GEOT"
    case geov = "GEOV"
    case gepa = "GEPA"
    case gepr = "GEPR"
    case gere = "GERE"
    case gest = "GEST"
    case geya = "GEYA"
    case geyo = "GEYO"
    case psca = "PSCA"
    case pses = "PSES"
    case psnc = "PSNC"
    case psnp = "PSNP"
    case psrg = "PSRG"
    case psss = "PSSS"
    case psst = "PSST"
    case pssw = "PSSW"

}
