//
// OBOverdraftTierbandSet1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Tier band set details */

public struct OBOverdraftTierbandSet1: Codable {

    public var tierBandMethod: OBTierBandType1Code
    public var overdraftType: OBOverdraftType1Code?
    /** Unique and unambiguous identification of a  Tier Band for a overdraft product. */
    public var identification: String?
    /** Indicates if the Overdraft is authorised (Y) or unauthorised (N) */
    public var authorisedIndicator: Bool?
    /** When a customer exceeds their credit limit, a financial institution will not charge the customer unauthorised overdraft charges if they do not exceed by more than the buffer amount. Note: Authorised overdraft charges may still apply. */
    public var bufferAmount: Double?
    /** Optional additional notes to supplement the overdraft Tier Band Set details */
    public var notes: [String]?
    /** Provides overdraft details for a specific tier or band */
    public var overdraftTierBand: [OBOverdraftTierBand1]
    /** Overdraft fees and charges details */
    public var overdraftFeesCharges: [OBOverdraftFeesCharges1]?

    public init(tierBandMethod: OBTierBandType1Code, overdraftType: OBOverdraftType1Code?, identification: String?, authorisedIndicator: Bool?, bufferAmount: Double?, notes: [String]?, overdraftTierBand: [OBOverdraftTierBand1], overdraftFeesCharges: [OBOverdraftFeesCharges1]?) {
        self.tierBandMethod = tierBandMethod
        self.overdraftType = overdraftType
        self.identification = identification
        self.authorisedIndicator = authorisedIndicator
        self.bufferAmount = bufferAmount
        self.notes = notes
        self.overdraftTierBand = overdraftTierBand
        self.overdraftFeesCharges = overdraftFeesCharges
    }

    public enum CodingKeys: String, CodingKey { 
        case tierBandMethod = "TierBandMethod"
        case overdraftType = "OverdraftType"
        case identification = "Identification"
        case authorisedIndicator = "AuthorisedIndicator"
        case bufferAmount = "BufferAmount"
        case notes = "Notes"
        case overdraftTierBand = "OverdraftTierBand"
        case overdraftFeesCharges = "OverdraftFeesCharges"
    }


}

