//
// OBProduct1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Product details associated with the Account */

public struct OBProduct1: Codable {

    /** The name of the Product used for marketing purposes from a customer perspective. I.e. what the customer would recognise. */
    public var productName: String?
    /** The unique ID that has been internally assigned by the financial institution to each of the current account banking products they market to their retail and/or small to medium enterprise (SME) customers. */
    public var productId: String?
    public var accountId: AccountId
    /** Any secondary Identification which  supports Product Identifier to uniquely identify the current account banking products. */
    public var secondaryProductId: String?
    public var productType: OBExternalProductType1Code
    /** Unique and unambiguous identification of a  Product Marketing State. */
    public var marketingStateId: String?
    public var otherProductType: OBOtherProductType1?

    public init(productName: String?, productId: String?, accountId: AccountId, secondaryProductId: String?, productType: OBExternalProductType1Code, marketingStateId: String?, otherProductType: OBOtherProductType1?) {
        self.productName = productName
        self.productId = productId
        self.accountId = accountId
        self.secondaryProductId = secondaryProductId
        self.productType = productType
        self.marketingStateId = marketingStateId
        self.otherProductType = otherProductType
    }

    public enum CodingKeys: String, CodingKey { 
        case productName = "ProductName"
        case productId = "ProductId"
        case accountId = "AccountId"
        case secondaryProductId = "SecondaryProductId"
        case productType = "ProductType"
        case marketingStateId = "MarketingStateId"
        case otherProductType = "OtherProductType"
    }


}

