//
// OBRepaymentAmountType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The repayment is for paying just the interest only or both interest and capital or bullet amount or balance to date etc */
public enum OBRepaymentAmountType1Code: String, Codable {
    case rabd = "RABD"
    case rabl = "RABL"
    case raci = "RACI"
    case rafc = "RAFC"
    case raio = "RAIO"
    case ralt = "RALT"
    case usot = "USOT"

}
