//
// OBReadBalance1Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadBalance1Data: Codable {

    /** Set of elements used to define the balance details. */
    public var balance: [OBCashBalance1]

    public init(balance: [OBCashBalance1]) {
        self.balance = balance
    }

    public enum CodingKeys: String, CodingKey { 
        case balance = "Balance"
    }


}

