//
// OBReadBeneficiary3Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadBeneficiary3Data: Codable {

    public var beneficiary: [OBBeneficiary3]?

    public init(beneficiary: [OBBeneficiary3]?) {
        self.beneficiary = beneficiary
    }

    public enum CodingKeys: String, CodingKey { 
        case beneficiary = "Beneficiary"
    }


}

