//
// OBReadAccount3Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadAccount3Data: Codable {

    /** Unambiguous identification of the account to which credit and debit entries are made. */
    public var account: [OBAccount3]?

    public init(account: [OBAccount3]?) {
        self.account = account
    }

    public enum CodingKeys: String, CodingKey { 
        case account = "Account"
    }


}

