//
// OBRepayment1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Repayment details of the Loan product */

public struct OBRepayment1: Codable {

    public var repaymentType: OBRepaymentType1Code?
    public var repaymentFrequency: OBRepaymentFrequency1Code?
    public var amountType: OBRepaymentAmountType1Code?
    /** Optional additional notes to supplement the Repayment */
    public var notes: [String]?
    public var otherRepaymentType: OBOtherCodeType1?
    public var otherRepaymentFrequency: OBOtherCodeType1?
    public var otherAmountType: OBOtherCodeType1?
    public var repaymentFeeCharges: OBRepaymentFeeCharges1?
    /** Details of capital repayment holiday if any */
    public var repaymentHoliday: [OBRepaymentHoliday1]?

    public init(repaymentType: OBRepaymentType1Code?, repaymentFrequency: OBRepaymentFrequency1Code?, amountType: OBRepaymentAmountType1Code?, notes: [String]?, otherRepaymentType: OBOtherCodeType1?, otherRepaymentFrequency: OBOtherCodeType1?, otherAmountType: OBOtherCodeType1?, repaymentFeeCharges: OBRepaymentFeeCharges1?, repaymentHoliday: [OBRepaymentHoliday1]?) {
        self.repaymentType = repaymentType
        self.repaymentFrequency = repaymentFrequency
        self.amountType = amountType
        self.notes = notes
        self.otherRepaymentType = otherRepaymentType
        self.otherRepaymentFrequency = otherRepaymentFrequency
        self.otherAmountType = otherAmountType
        self.repaymentFeeCharges = repaymentFeeCharges
        self.repaymentHoliday = repaymentHoliday
    }

    public enum CodingKeys: String, CodingKey { 
        case repaymentType = "RepaymentType"
        case repaymentFrequency = "RepaymentFrequency"
        case amountType = "AmountType"
        case notes = "Notes"
        case otherRepaymentType = "OtherRepaymentType"
        case otherRepaymentFrequency = "OtherRepaymentFrequency"
        case otherAmountType = "OtherAmountType"
        case repaymentFeeCharges = "RepaymentFeeCharges"
        case repaymentHoliday = "RepaymentHoliday"
    }


}

