//
// OBScheduledPayment2Basic.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBScheduledPayment2Basic: Codable {

    public var accountId: AccountId
    /** A unique and immutable identifier used to identify the scheduled payment resource. This identifier has no meaning to the account owner. */
    public var scheduledPaymentId: String?
    /** The date on which the scheduled payment will be made. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var scheduledPaymentDateTime: Date
    public var scheduledType: OBExternalScheduleType1Code
    /** Unique reference, as assigned by the creditor, to unambiguously refer to the payment transaction. Usage: If available, the initiating party should provide this reference in the structured remittance information, to enable reconciliation by the creditor upon receipt of the amount of money. If the business context requires the use of a creditor reference or a payment remit identification, and only one identifier can be passed through the end-to-end chain, the creditor&#39;s reference or payment remittance identification should be quoted in the end-to-end transaction identification. */
    public var reference: String?
    public var instructedAmount: OBActiveOrHistoricCurrencyAndAmount

    public init(accountId: AccountId, scheduledPaymentId: String?, scheduledPaymentDateTime: Date, scheduledType: OBExternalScheduleType1Code, reference: String?, instructedAmount: OBActiveOrHistoricCurrencyAndAmount) {
        self.accountId = accountId
        self.scheduledPaymentId = scheduledPaymentId
        self.scheduledPaymentDateTime = scheduledPaymentDateTime
        self.scheduledType = scheduledType
        self.reference = reference
        self.instructedAmount = instructedAmount
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "AccountId"
        case scheduledPaymentId = "ScheduledPaymentId"
        case scheduledPaymentDateTime = "ScheduledPaymentDateTime"
        case scheduledType = "ScheduledType"
        case reference = "Reference"
        case instructedAmount = "InstructedAmount"
    }


}

