//
// OBStatementFee2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to provide details of a fee for the statement resource. */

public struct OBStatementFee2: Codable {

    public enum CreditDebitIndicator: String, Codable { 
        case credit = "Credit"
        case debit = "Debit"
    }
    /** Description that may be available for the statement fee. */
    public var _description: String?
    /** Indicates whether the amount is a credit or a debit.  Usage: A zero amount is considered to be a credit amount. */
    public var creditDebitIndicator: CreditDebitIndicator
    public var type: OBExternalStatementFeeType1Code
    /** Rate charged for Statement Fee (where it is charged in terms of a rate rather than an amount) */
    public var rate: Double?
    public var rateType: OBExternalStatementFeeRateType1Code?
    public var frequency: OBExternalStatementFeeFrequency1Code?
    public var amount: OBActiveOrHistoricCurrencyAndAmount

    public init(_description: String?, creditDebitIndicator: CreditDebitIndicator, type: OBExternalStatementFeeType1Code, rate: Double?, rateType: OBExternalStatementFeeRateType1Code?, frequency: OBExternalStatementFeeFrequency1Code?, amount: OBActiveOrHistoricCurrencyAndAmount) {
        self._description = _description
        self.creditDebitIndicator = creditDebitIndicator
        self.type = type
        self.rate = rate
        self.rateType = rateType
        self.frequency = frequency
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "Description"
        case creditDebitIndicator = "CreditDebitIndicator"
        case type = "Type"
        case rate = "Rate"
        case rateType = "RateType"
        case frequency = "Frequency"
        case amount = "Amount"
    }


}

