//
// OBStatementBenefit1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to provide details of a benefit or reward amount for the statement resource. */

public struct OBStatementBenefit1: Codable {

    public var type: OBExternalStatementBenefitType1Code
    public var amount: OBActiveOrHistoricCurrencyAndAmount

    public init(type: OBExternalStatementBenefitType1Code, amount: OBActiveOrHistoricCurrencyAndAmount) {
        self.type = type
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "Type"
        case amount = "Amount"
    }


}

