//
// OBTierBand1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Tier Band Details */

public struct OBTierBand1: Codable {

    /** Unique and unambiguous identification of a  Tier Band for the Product. */
    public var identification: String?
    /** Minimum deposit value for which the credit interest tier applies. */
    public var tierValueMinimum: Double
    /** Minimum deposit value for which the credit interest tier applies. */
    public var tierValueMaximum: Double?
    public var calculationFrequency: OBFrequency1Code?
    public var applicationFrequency: OBFrequency1Code
    public var depositInterestAppliedCoverage: OBTierBandType1Code?
    public var fixedVariableInterestRateType: OBInterestFixedVariableType1Code
    /** Minimum deposit value for which the credit interest tier applies. */
    public var AER: Double
    public var bankInterestRateType: OBInterestRateType1Code?
    /** Minimum deposit value for which the credit interest tier applies. */
    public var bankInterestRate: Double?
    /** Optional additional notes to supplement the Tier Band details */
    public var notes: [String]?
    public var otherBankInterestType: OBOtherCodeType1?
    public var otherApplicationFrequency: OBOtherCodeType1?
    public var otherCalculationFrequency: OBOtherCodeType1?

    public init(identification: String?, tierValueMinimum: Double, tierValueMaximum: Double?, calculationFrequency: OBFrequency1Code?, applicationFrequency: OBFrequency1Code, depositInterestAppliedCoverage: OBTierBandType1Code?, fixedVariableInterestRateType: OBInterestFixedVariableType1Code, AER: Double, bankInterestRateType: OBInterestRateType1Code?, bankInterestRate: Double?, notes: [String]?, otherBankInterestType: OBOtherCodeType1?, otherApplicationFrequency: OBOtherCodeType1?, otherCalculationFrequency: OBOtherCodeType1?) {
        self.identification = identification
        self.tierValueMinimum = tierValueMinimum
        self.tierValueMaximum = tierValueMaximum
        self.calculationFrequency = calculationFrequency
        self.applicationFrequency = applicationFrequency
        self.depositInterestAppliedCoverage = depositInterestAppliedCoverage
        self.fixedVariableInterestRateType = fixedVariableInterestRateType
        self.AER = AER
        self.bankInterestRateType = bankInterestRateType
        self.bankInterestRate = bankInterestRate
        self.notes = notes
        self.otherBankInterestType = otherBankInterestType
        self.otherApplicationFrequency = otherApplicationFrequency
        self.otherCalculationFrequency = otherCalculationFrequency
    }

    public enum CodingKeys: String, CodingKey { 
        case identification = "Identification"
        case tierValueMinimum = "TierValueMinimum"
        case tierValueMaximum = "TierValueMaximum"
        case calculationFrequency = "CalculationFrequency"
        case applicationFrequency = "ApplicationFrequency"
        case depositInterestAppliedCoverage = "DepositInterestAppliedCoverage"
        case fixedVariableInterestRateType = "FixedVariableInterestRateType"
        case AER
        case bankInterestRateType = "BankInterestRateType"
        case bankInterestRate = "BankInterestRate"
        case notes = "Notes"
        case otherBankInterestType = "OtherBankInterestType"
        case otherApplicationFrequency = "OtherApplicationFrequency"
        case otherCalculationFrequency = "OtherCalculationFrequency"
    }


}

