//
// Overdraft.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Borrowing details */

public struct Overdraft: Codable {

    /** Associated Notes about the overdraft rates */
    public var notes: [String]?
    /** Tier band set details */
    public var overdraftTierBandSet: [OverdraftOverdraftTierBandSet]

    public init(notes: [String]?, overdraftTierBandSet: [OverdraftOverdraftTierBandSet]) {
        self.notes = notes
        self.overdraftTierBandSet = overdraftTierBandSet
    }

    public enum CodingKeys: String, CodingKey { 
        case notes = "Notes"
        case overdraftTierBandSet = "OverdraftTierBandSet"
    }


}

