//
// AddressLine.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Information that locates and identifies a specific address for a transaction entry, that is presented in free format text. */

public struct AddressLine: Codable {




}

