//
// Description2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Description that may be available for the statement interest. */

public struct Description2: Codable {




}

