//
// Description3.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Description to describe the purpose of the code */

public struct Description3: Codable {




}

