//
// Description0.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the description of the account type. */

public struct Description0: Codable {




}

