//
// Identification2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Unique and unambiguous identification of a financial institution or a branch of a financial institution. */

public struct Identification2: Codable {




}

