//
// Name3.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Long name associated with the code */

public struct Name3: Codable {




}

