//
// OBActiveOrHistoricCurrencyAndAmount8.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Transaction charges to be paid by the charge bearer. */

public struct OBActiveOrHistoricCurrencyAndAmount8: Codable {

    public var amount: OBActiveCurrencyAndAmountSimpleType
    public var currency: ActiveOrHistoricCurrencyCode1

    public init(amount: OBActiveCurrencyAndAmountSimpleType, currency: ActiveOrHistoricCurrencyCode1) {
        self.amount = amount
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey { 
        case amount = "Amount"
        case currency = "Currency"
    }


}

