//
// OBCashAccount61.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Unambiguous identification of the account of the debtor, in the case of a crebit transaction. */

public struct OBCashAccount61: Codable {

    public var schemeName: OBExternalAccountIdentification4Code?
    public var identification: Identification0?
    public var name: Name0?
    public var secondaryIdentification: SecondaryIdentification?

    public init(schemeName: OBExternalAccountIdentification4Code?, identification: Identification0?, name: Name0?, secondaryIdentification: SecondaryIdentification?) {
        self.schemeName = schemeName
        self.identification = identification
        self.name = name
        self.secondaryIdentification = secondaryIdentification
    }

    public enum CodingKeys: String, CodingKey { 
        case schemeName = "SchemeName"
        case identification = "Identification"
        case name = "Name"
        case secondaryIdentification = "SecondaryIdentification"
    }


}

