//
// OBCodeMnemonic.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The four letter Mnemonic used within an XML file to identify a code */

public struct OBCodeMnemonic: Codable {




}

