//
// OBCreditDebitCode2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Indicates whether the balance is a credit or a debit balance.  Usage: A zero balance is considered to be a credit balance. */
public enum OBCreditDebitCode2: String, Codable {
    case credit = "Credit"
    case debit = "Debit"

}
