//
// OBExternalPartyType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Party type, in a coded form. */
public enum OBExternalPartyType1Code: String, Codable {
    case delegate = "Delegate"
    case joint = "Joint"
    case sole = "Sole"

}
