//
// OBFeeFrequency1Code3.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** How frequently the fee/charge is calculated */
public enum OBFeeFrequency1Code3: String, Codable {
    case feac = "FEAC"
    case feao = "FEAO"
    case fecp = "FECP"
    case feda = "FEDA"
    case feho = "FEHO"
    case fei = "FEI"
    case femo = "FEMO"
    case feoa = "FEOA"
    case feot = "FEOT"
    case fepc = "FEPC"
    case feph = "FEPH"
    case fepo = "FEPO"
    case feps = "FEPS"
    case fept = "FEPT"
    case fepta = "FEPTA"
    case feptp = "FEPTP"
    case fequ = "FEQU"
    case fesm = "FESM"
    case fest = "FEST"
    case fewe = "FEWE"
    case feye = "FEYE"

}
