//
// OBInterestRateType1Code0.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount) */
public enum OBInterestRateType1Code0: String, Codable {
    case inbb = "INBB"
    case infr = "INFR"
    case ingr = "INGR"
    case inlr = "INLR"
    case inne = "INNE"
    case inot = "INOT"

}
