//
// OBParty2Address.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Postal address of a party. */

public struct OBParty2Address: Codable {

    public var addressType: OBAddressTypeCode?
    public var addressLine: [String]?
    public var streetName: StreetName?
    public var buildingNumber: BuildingNumber?
    public var postCode: PostCode?
    public var townName: TownName?
    public var countrySubDivision: CountrySubDivision?
    public var country: CountryCode

    public init(addressType: OBAddressTypeCode?, addressLine: [String]?, streetName: StreetName?, buildingNumber: BuildingNumber?, postCode: PostCode?, townName: TownName?, countrySubDivision: CountrySubDivision?, country: CountryCode) {
        self.addressType = addressType
        self.addressLine = addressLine
        self.streetName = streetName
        self.buildingNumber = buildingNumber
        self.postCode = postCode
        self.townName = townName
        self.countrySubDivision = countrySubDivision
        self.country = country
    }

    public enum CodingKeys: String, CodingKey { 
        case addressType = "AddressType"
        case addressLine = "AddressLine"
        case streetName = "StreetName"
        case buildingNumber = "BuildingNumber"
        case postCode = "PostCode"
        case townName = "TownName"
        case countrySubDivision = "CountrySubDivision"
        case country = "Country"
    }


}

