//
// OBParty2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBParty2: Codable {

    public var partyId: PartyId
    public var partyNumber: PartyNumber?
    public var partyType: OBExternalPartyType1Code?
    public var name: Name1?
    public var fullLegalName: FullLegalName?
    public var legalStructure: OBExternalLegalStructureType1Code?
    public var beneficialOwnership: Bool?
    public var accountRole: OBExternalAccountRole1Code?
    public var emailAddress: EmailAddress?
    public var phone: PhoneNumber0?
    public var mobile: PhoneNumber1?
    public var relationships: OBPartyRelationships1?
    public var address: [OBParty2Address]?

    public init(partyId: PartyId, partyNumber: PartyNumber?, partyType: OBExternalPartyType1Code?, name: Name1?, fullLegalName: FullLegalName?, legalStructure: OBExternalLegalStructureType1Code?, beneficialOwnership: Bool?, accountRole: OBExternalAccountRole1Code?, emailAddress: EmailAddress?, phone: PhoneNumber0?, mobile: PhoneNumber1?, relationships: OBPartyRelationships1?, address: [OBParty2Address]?) {
        self.partyId = partyId
        self.partyNumber = partyNumber
        self.partyType = partyType
        self.name = name
        self.fullLegalName = fullLegalName
        self.legalStructure = legalStructure
        self.beneficialOwnership = beneficialOwnership
        self.accountRole = accountRole
        self.emailAddress = emailAddress
        self.phone = phone
        self.mobile = mobile
        self.relationships = relationships
        self.address = address
    }

    public enum CodingKeys: String, CodingKey { 
        case partyId = "PartyId"
        case partyNumber = "PartyNumber"
        case partyType = "PartyType"
        case name = "Name"
        case fullLegalName = "FullLegalName"
        case legalStructure = "LegalStructure"
        case beneficialOwnership = "BeneficialOwnership"
        case accountRole = "AccountRole"
        case emailAddress = "EmailAddress"
        case phone = "Phone"
        case mobile = "Mobile"
        case relationships = "Relationships"
        case address = "Address"
    }


}

