//
// OBRate11.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount) */

public struct OBRate11: Codable {




}

