//
// OBReadProduct2DataOtherProductTypeOverdraft.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Borrowing details */

public struct OBReadProduct2DataOtherProductTypeOverdraft: Codable {

    public var notes: [String]?
    public var overdraftTierBandSet: [OBReadProduct2DataOtherProductTypeOverdraftOverdraftTierBandSet]

    public init(notes: [String]?, overdraftTierBandSet: [OBReadProduct2DataOtherProductTypeOverdraftOverdraftTierBandSet]) {
        self.notes = notes
        self.overdraftTierBandSet = overdraftTierBandSet
    }

    public enum CodingKeys: String, CodingKey { 
        case notes = "Notes"
        case overdraftTierBandSet = "OverdraftTierBandSet"
    }


}

