//
// OBReadBalance1DataBalance.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to define the balance details. */

public struct OBReadBalance1DataBalance: Codable {

    public var accountId: AccountId
    public var creditDebitIndicator: OBCreditDebitCode2
    public var type: OBBalanceType1Code
    /** Indicates the date (and time) of the balance.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var dateTime: Date
    public var amount: OBReadBalance1DataAmount
    public var creditLine: [OBReadBalance1DataCreditLine]?

    public init(accountId: AccountId, creditDebitIndicator: OBCreditDebitCode2, type: OBBalanceType1Code, dateTime: Date, amount: OBReadBalance1DataAmount, creditLine: [OBReadBalance1DataCreditLine]?) {
        self.accountId = accountId
        self.creditDebitIndicator = creditDebitIndicator
        self.type = type
        self.dateTime = dateTime
        self.amount = amount
        self.creditLine = creditLine
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "AccountId"
        case creditDebitIndicator = "CreditDebitIndicator"
        case type = "Type"
        case dateTime = "DateTime"
        case amount = "Amount"
        case creditLine = "CreditLine"
    }


}

