//
// OBReadDataStatement2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadDataStatement2: Codable {

    public var statement: [OBStatement2]?

    public init(statement: [OBStatement2]?) {
        self.statement = statement
    }

    public enum CodingKeys: String, CodingKey { 
        case statement = "Statement"
    }


}

