//
// OBReadProduct2DataOtherProductTypeRepaymentRepaymentHoliday.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of capital repayment holiday if any */

public struct OBReadProduct2DataOtherProductTypeRepaymentRepaymentHoliday: Codable {

    public enum MaxHolidayPeriod: String, Codable { 
        case pact = "PACT"
        case pday = "PDAY"
        case phyr = "PHYR"
        case pmth = "PMTH"
        case pqtr = "PQTR"
        case pwek = "PWEK"
        case pyer = "PYER"
    }
    /** The maximum length/duration of a Repayment Holiday */
    public var maxHolidayLength: Int?
    /** The unit of period (days, weeks, months etc.) of the repayment holiday */
    public var maxHolidayPeriod: MaxHolidayPeriod?
    public var notes: [String]?

    public init(maxHolidayLength: Int?, maxHolidayPeriod: MaxHolidayPeriod?, notes: [String]?) {
        self.maxHolidayLength = maxHolidayLength
        self.maxHolidayPeriod = maxHolidayPeriod
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey { 
        case maxHolidayLength = "MaxHolidayLength"
        case maxHolidayPeriod = "MaxHolidayPeriod"
        case notes = "Notes"
    }


}

