//
// OBReadParty1DataParty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadParty1DataParty: Codable {

    public var partyId: PartyId
    public var partyNumber: PartyNumber?
    public var partyType: OBExternalPartyType1Code?
    public var name: Name1?
    public var emailAddress: EmailAddress?
    public var phone: PhoneNumber0?
    public var mobile: PhoneNumber1?
    public var address: [OBParty2Address]?

    public init(partyId: PartyId, partyNumber: PartyNumber?, partyType: OBExternalPartyType1Code?, name: Name1?, emailAddress: EmailAddress?, phone: PhoneNumber0?, mobile: PhoneNumber1?, address: [OBParty2Address]?) {
        self.partyId = partyId
        self.partyNumber = partyNumber
        self.partyType = partyType
        self.name = name
        self.emailAddress = emailAddress
        self.phone = phone
        self.mobile = mobile
        self.address = address
    }

    public enum CodingKeys: String, CodingKey { 
        case partyId = "PartyId"
        case partyNumber = "PartyNumber"
        case partyType = "PartyType"
        case name = "Name"
        case emailAddress = "EmailAddress"
        case phone = "Phone"
        case mobile = "Mobile"
        case address = "Address"
    }


}

