//
// OBReadProduct2DataOtherProductTypeLoanInterestLoanInterestFeeChargeCap.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about any caps (minimum/maximum charges) that apply to a particular fee/charge */

public struct OBReadProduct2DataOtherProductTypeLoanInterestLoanInterestFeeChargeCap: Codable {

    public enum FeeType: String, Codable { 
        case fepf = "FEPF"
        case ftot = "FTOT"
        case fyaf = "FYAF"
        case fyam = "FYAM"
        case fyaq = "FYAQ"
        case fycp = "FYCP"
        case fydb = "FYDB"
        case fymi = "FYMI"
        case fyxx = "FYXX"
    }
    public var feeType: [FeeType]
    public var minMaxType: OBMinMaxType1Code
    public var feeCapOccurrence: Number1?
    public var feeCapAmount: OBAmount14?
    public var cappingPeriod: OBFeeFrequency1Code4?
    public var notes: [String]?
    public var otherFeeType: [OBReadProduct2DataOtherProductTypeOverdraftOtherFeeType]?

    public init(feeType: [FeeType], minMaxType: OBMinMaxType1Code, feeCapOccurrence: Number1?, feeCapAmount: OBAmount14?, cappingPeriod: OBFeeFrequency1Code4?, notes: [String]?, otherFeeType: [OBReadProduct2DataOtherProductTypeOverdraftOtherFeeType]?) {
        self.feeType = feeType
        self.minMaxType = minMaxType
        self.feeCapOccurrence = feeCapOccurrence
        self.feeCapAmount = feeCapAmount
        self.cappingPeriod = cappingPeriod
        self.notes = notes
        self.otherFeeType = otherFeeType
    }

    public enum CodingKeys: String, CodingKey { 
        case feeType = "FeeType"
        case minMaxType = "MinMaxType"
        case feeCapOccurrence = "FeeCapOccurrence"
        case feeCapAmount = "FeeCapAmount"
        case cappingPeriod = "CappingPeriod"
        case notes = "Notes"
        case otherFeeType = "OtherFeeType"
    }


}

