//
// OBReadProduct2DataOtherProductTypeLoanInterestLoanInterestFeesCharges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains details of fees and charges which are not associated with either LoanRepayment or features/benefits */

public struct OBReadProduct2DataOtherProductTypeLoanInterestLoanInterestFeesCharges: Codable {

    public var loanInterestFeeChargeDetail: [OBReadProduct2DataOtherProductTypeLoanInterestLoanInterestFeeChargeDetail]
    public var loanInterestFeeChargeCap: [OBReadProduct2DataOtherProductTypeLoanInterestLoanInterestFeeChargeCap]?

    public init(loanInterestFeeChargeDetail: [OBReadProduct2DataOtherProductTypeLoanInterestLoanInterestFeeChargeDetail], loanInterestFeeChargeCap: [OBReadProduct2DataOtherProductTypeLoanInterestLoanInterestFeeChargeCap]?) {
        self.loanInterestFeeChargeDetail = loanInterestFeeChargeDetail
        self.loanInterestFeeChargeCap = loanInterestFeeChargeCap
    }

    public enum CodingKeys: String, CodingKey { 
        case loanInterestFeeChargeDetail = "LoanInterestFeeChargeDetail"
        case loanInterestFeeChargeCap = "LoanInterestFeeChargeCap"
    }


}

