//
// OBReadProduct2DataProduct.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Product details associated with the Account */

public struct OBReadProduct2DataProduct: Codable {

    public enum ProductType: String, Codable { 
        case businessCurrentAccount = "BusinessCurrentAccount"
        case commercialCreditCard = "CommercialCreditCard"
        case other = "Other"
        case personalCurrentAccount = "PersonalCurrentAccount"
        case smeloan = "SMELoan"
    }
    /** The name of the Product used for marketing purposes from a customer perspective. I.e. what the customer would recognise. */
    public var productName: String?
    /** The unique ID that has been internally assigned by the financial institution to each of the current account banking products they market to their retail and/or small to medium enterprise (SME) customers. */
    public var productId: String?
    /** Account Identification of the customer for Product Details */
    public var accountId: String
    /** Any secondary Identification which  supports Product Identifier to uniquely identify the current account banking products. */
    public var secondaryProductId: String?
    /** Product type : Personal Current Account, Business Current Account */
    public var productType: ProductType
    /** Unique and unambiguous identification of a  Product Marketing State. */
    public var marketingStateId: String?
    public var otherProductType: OBReadProduct2DataOtherProductType?
    public var BCA: BCA?
    public var PCA: PCA?

    public init(productName: String?, productId: String?, accountId: String, secondaryProductId: String?, productType: ProductType, marketingStateId: String?, otherProductType: OBReadProduct2DataOtherProductType?, BCA: BCA?, PCA: PCA?) {
        self.productName = productName
        self.productId = productId
        self.accountId = accountId
        self.secondaryProductId = secondaryProductId
        self.productType = productType
        self.marketingStateId = marketingStateId
        self.otherProductType = otherProductType
        self.BCA = BCA
        self.PCA = PCA
    }

    public enum CodingKeys: String, CodingKey { 
        case productName = "ProductName"
        case productId = "ProductId"
        case accountId = "AccountId"
        case secondaryProductId = "SecondaryProductId"
        case productType = "ProductType"
        case marketingStateId = "MarketingStateId"
        case otherProductType = "OtherProductType"
        case BCA
        case PCA
    }


}

