//
// OBReadStandingOrder4Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadStandingOrder4Data: Codable {

    public var standingOrder: [OBStandingOrder4]?

    public init(standingOrder: [OBStandingOrder4]?) {
        self.standingOrder = standingOrder
    }

    public enum CodingKeys: String, CodingKey { 
        case standingOrder = "StandingOrder"
    }


}

