//
// OBReadConsentResponse1Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadConsentResponse1Data: Codable {

    public enum Status: String, Codable { 
        case authorised = "Authorised"
        case awaitingAuthorisation = "AwaitingAuthorisation"
        case rejected = "Rejected"
        case revoked = "Revoked"
    }
    public enum Permissions: String, Codable { 
        case readAccountsBasic = "ReadAccountsBasic"
        case readAccountsDetail = "ReadAccountsDetail"
        case readBalances = "ReadBalances"
        case readBeneficiariesBasic = "ReadBeneficiariesBasic"
        case readBeneficiariesDetail = "ReadBeneficiariesDetail"
        case readDirectDebits = "ReadDirectDebits"
        case readOffers = "ReadOffers"
        case readPAN = "ReadPAN"
        case readParty = "ReadParty"
        case readPartyPSU = "ReadPartyPSU"
        case readProducts = "ReadProducts"
        case readScheduledPaymentsBasic = "ReadScheduledPaymentsBasic"
        case readScheduledPaymentsDetail = "ReadScheduledPaymentsDetail"
        case readStandingOrdersBasic = "ReadStandingOrdersBasic"
        case readStandingOrdersDetail = "ReadStandingOrdersDetail"
        case readStatementsBasic = "ReadStatementsBasic"
        case readStatementsDetail = "ReadStatementsDetail"
        case readTransactionsBasic = "ReadTransactionsBasic"
        case readTransactionsCredits = "ReadTransactionsCredits"
        case readTransactionsDebits = "ReadTransactionsDebits"
        case readTransactionsDetail = "ReadTransactionsDetail"
    }
    /** Unique identification as assigned to identify the account access consent resource. */
    public var consentId: String
    public var creationDateTime: CreationDateTime
    /** Specifies the status of consent resource in code form. */
    public var status: Status
    public var statusUpdateDateTime: StatusUpdateDateTime
    public var permissions: [Permissions]
    /** Specified date and time the permissions will expire. If this is not populated, the permissions will be open ended.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var expirationDateTime: Date?
    /** Specified start date and time for the transaction query period. If this is not populated, the start date will be open ended, and data will be returned from the earliest available transaction.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var transactionFromDateTime: Date?
    /** Specified end date and time for the transaction query period. If this is not populated, the end date will be open ended, and data will be returned to the latest available transaction.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 */
    public var transactionToDateTime: Date?

    public init(consentId: String, creationDateTime: CreationDateTime, status: Status, statusUpdateDateTime: StatusUpdateDateTime, permissions: [Permissions], expirationDateTime: Date?, transactionFromDateTime: Date?, transactionToDateTime: Date?) {
        self.consentId = consentId
        self.creationDateTime = creationDateTime
        self.status = status
        self.statusUpdateDateTime = statusUpdateDateTime
        self.permissions = permissions
        self.expirationDateTime = expirationDateTime
        self.transactionFromDateTime = transactionFromDateTime
        self.transactionToDateTime = transactionToDateTime
    }

    public enum CodingKeys: String, CodingKey { 
        case consentId = "ConsentId"
        case creationDateTime = "CreationDateTime"
        case status = "Status"
        case statusUpdateDateTime = "StatusUpdateDateTime"
        case permissions = "Permissions"
        case expirationDateTime = "ExpirationDateTime"
        case transactionFromDateTime = "TransactionFromDateTime"
        case transactionToDateTime = "TransactionToDateTime"
    }


}

