//
// OBStatement2StatementFee.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to provide details of a fee for the statement resource. */

public struct OBStatement2StatementFee: Codable {

    public var _description: Description1?
    public var creditDebitIndicator: OBCreditDebitCode0
    public var type: OBExternalStatementFeeType1Code
    public var rate: OBRate10?
    public var rateType: OBExternalStatementFeeRateType1Code?
    public var frequency: OBExternalStatementFeeFrequency1Code?
    public var amount: OBActiveOrHistoricCurrencyAndAmount4

    public init(_description: Description1?, creditDebitIndicator: OBCreditDebitCode0, type: OBExternalStatementFeeType1Code, rate: OBRate10?, rateType: OBExternalStatementFeeRateType1Code?, frequency: OBExternalStatementFeeFrequency1Code?, amount: OBActiveOrHistoricCurrencyAndAmount4) {
        self._description = _description
        self.creditDebitIndicator = creditDebitIndicator
        self.type = type
        self.rate = rate
        self.rateType = rateType
        self.frequency = frequency
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "Description"
        case creditDebitIndicator = "CreditDebitIndicator"
        case type = "Type"
        case rate = "Rate"
        case rateType = "RateType"
        case frequency = "Frequency"
        case amount = "Amount"
    }


}

