//
// OBStatement2StatementBenefit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to provide details of a benefit or reward amount for the statement resource. */

public struct OBStatement2StatementBenefit: Codable {

    public var type: OBExternalStatementBenefitType1Code
    public var amount: OBActiveOrHistoricCurrencyAndAmount3

    public init(type: OBExternalStatementBenefitType1Code, amount: OBActiveOrHistoricCurrencyAndAmount3) {
        self.type = type
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "Type"
        case amount = "Amount"
    }


}

