//
// OBStatement2StatementDateTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to provide details of a generic date time for the statement resource. */

public struct OBStatement2StatementDateTime: Codable {

    public var dateTime: Date
    public var type: OBExternalStatementDateTimeType1Code

    public init(dateTime: Date, type: OBExternalStatementDateTimeType1Code) {
        self.dateTime = dateTime
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case dateTime = "DateTime"
        case type = "Type"
    }


}

