//
// OBTransaction5Basic.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Provides further details on an entry in the report. */

public struct OBTransaction5Basic: Codable {

    public var accountId: AccountId
    public var transactionId: TransactionId?
    public var transactionReference: TransactionReference?
    public var statementReference: [StatementReference]?
    public var creditDebitIndicator: OBCreditDebitCode1
    public var status: OBEntryStatus1Code
    public var bookingDateTime: BookingDateTime
    public var valueDateTime: ValueDateTime?
    public var addressLine: AddressLine?
    public var amount: OBActiveOrHistoricCurrencyAndAmount7
    public var chargeAmount: OBActiveOrHistoricCurrencyAndAmount8?
    public var currencyExchange: OBCurrencyExchange5?
    public var bankTransactionCode: OBBankTransactionCodeStructure1?
    public var proprietaryBankTransactionCode: ProprietaryBankTransactionCodeStructure1?
    public var cardInstrument: OBTransactionCardInstrument1?
    public var supplementaryData: OBSupplementaryData1?

    public init(accountId: AccountId, transactionId: TransactionId?, transactionReference: TransactionReference?, statementReference: [StatementReference]?, creditDebitIndicator: OBCreditDebitCode1, status: OBEntryStatus1Code, bookingDateTime: BookingDateTime, valueDateTime: ValueDateTime?, addressLine: AddressLine?, amount: OBActiveOrHistoricCurrencyAndAmount7, chargeAmount: OBActiveOrHistoricCurrencyAndAmount8?, currencyExchange: OBCurrencyExchange5?, bankTransactionCode: OBBankTransactionCodeStructure1?, proprietaryBankTransactionCode: ProprietaryBankTransactionCodeStructure1?, cardInstrument: OBTransactionCardInstrument1?, supplementaryData: OBSupplementaryData1?) {
        self.accountId = accountId
        self.transactionId = transactionId
        self.transactionReference = transactionReference
        self.statementReference = statementReference
        self.creditDebitIndicator = creditDebitIndicator
        self.status = status
        self.bookingDateTime = bookingDateTime
        self.valueDateTime = valueDateTime
        self.addressLine = addressLine
        self.amount = amount
        self.chargeAmount = chargeAmount
        self.currencyExchange = currencyExchange
        self.bankTransactionCode = bankTransactionCode
        self.proprietaryBankTransactionCode = proprietaryBankTransactionCode
        self.cardInstrument = cardInstrument
        self.supplementaryData = supplementaryData
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "AccountId"
        case transactionId = "TransactionId"
        case transactionReference = "TransactionReference"
        case statementReference = "StatementReference"
        case creditDebitIndicator = "CreditDebitIndicator"
        case status = "Status"
        case bookingDateTime = "BookingDateTime"
        case valueDateTime = "ValueDateTime"
        case addressLine = "AddressLine"
        case amount = "Amount"
        case chargeAmount = "ChargeAmount"
        case currencyExchange = "CurrencyExchange"
        case bankTransactionCode = "BankTransactionCode"
        case proprietaryBankTransactionCode = "ProprietaryBankTransactionCode"
        case cardInstrument = "CardInstrument"
        case supplementaryData = "SupplementaryData"
    }


}

