//
// OBTransaction5.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Provides further details on an entry in the report. */

public struct OBTransaction5: Codable {

    public var accountId: AccountId
    public var transactionId: TransactionId?
    public var transactionReference: TransactionReference?
    public var statementReference: [StatementReference]?
    public var creditDebitIndicator: OBCreditDebitCode1
    public var status: OBEntryStatus1Code
    public var bookingDateTime: BookingDateTime
    public var valueDateTime: ValueDateTime?
    public var transactionInformation: TransactionInformation?
    public var addressLine: AddressLine?
    public var amount: OBActiveOrHistoricCurrencyAndAmount7
    public var chargeAmount: OBActiveOrHistoricCurrencyAndAmount8?
    public var currencyExchange: OBCurrencyExchange5?
    public var bankTransactionCode: OBBankTransactionCodeStructure1?
    public var proprietaryBankTransactionCode: ProprietaryBankTransactionCodeStructure1?
    public var balance: OBTransactionCashBalance?
    public var merchantDetails: OBMerchantDetails1?
    public var creditorAgent: OBBranchAndFinancialInstitutionIdentification60?
    public var creditorAccount: OBCashAccount60?
    public var debtorAgent: OBBranchAndFinancialInstitutionIdentification61?
    public var debtorAccount: OBCashAccount61?
    public var cardInstrument: OBTransactionCardInstrument1?
    public var supplementaryData: OBSupplementaryData1?

    public init(accountId: AccountId, transactionId: TransactionId?, transactionReference: TransactionReference?, statementReference: [StatementReference]?, creditDebitIndicator: OBCreditDebitCode1, status: OBEntryStatus1Code, bookingDateTime: BookingDateTime, valueDateTime: ValueDateTime?, transactionInformation: TransactionInformation?, addressLine: AddressLine?, amount: OBActiveOrHistoricCurrencyAndAmount7, chargeAmount: OBActiveOrHistoricCurrencyAndAmount8?, currencyExchange: OBCurrencyExchange5?, bankTransactionCode: OBBankTransactionCodeStructure1?, proprietaryBankTransactionCode: ProprietaryBankTransactionCodeStructure1?, balance: OBTransactionCashBalance?, merchantDetails: OBMerchantDetails1?, creditorAgent: OBBranchAndFinancialInstitutionIdentification60?, creditorAccount: OBCashAccount60?, debtorAgent: OBBranchAndFinancialInstitutionIdentification61?, debtorAccount: OBCashAccount61?, cardInstrument: OBTransactionCardInstrument1?, supplementaryData: OBSupplementaryData1?) {
        self.accountId = accountId
        self.transactionId = transactionId
        self.transactionReference = transactionReference
        self.statementReference = statementReference
        self.creditDebitIndicator = creditDebitIndicator
        self.status = status
        self.bookingDateTime = bookingDateTime
        self.valueDateTime = valueDateTime
        self.transactionInformation = transactionInformation
        self.addressLine = addressLine
        self.amount = amount
        self.chargeAmount = chargeAmount
        self.currencyExchange = currencyExchange
        self.bankTransactionCode = bankTransactionCode
        self.proprietaryBankTransactionCode = proprietaryBankTransactionCode
        self.balance = balance
        self.merchantDetails = merchantDetails
        self.creditorAgent = creditorAgent
        self.creditorAccount = creditorAccount
        self.debtorAgent = debtorAgent
        self.debtorAccount = debtorAccount
        self.cardInstrument = cardInstrument
        self.supplementaryData = supplementaryData
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "AccountId"
        case transactionId = "TransactionId"
        case transactionReference = "TransactionReference"
        case statementReference = "StatementReference"
        case creditDebitIndicator = "CreditDebitIndicator"
        case status = "Status"
        case bookingDateTime = "BookingDateTime"
        case valueDateTime = "ValueDateTime"
        case transactionInformation = "TransactionInformation"
        case addressLine = "AddressLine"
        case amount = "Amount"
        case chargeAmount = "ChargeAmount"
        case currencyExchange = "CurrencyExchange"
        case bankTransactionCode = "BankTransactionCode"
        case proprietaryBankTransactionCode = "ProprietaryBankTransactionCode"
        case balance = "Balance"
        case merchantDetails = "MerchantDetails"
        case creditorAgent = "CreditorAgent"
        case creditorAccount = "CreditorAccount"
        case debtorAgent = "DebtorAgent"
        case debtorAccount = "DebtorAccount"
        case cardInstrument = "CardInstrument"
        case supplementaryData = "SupplementaryData"
    }


}

