//
// ProductDetails1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProductDetails1: Codable {

    public enum Segment: String, Codable { 
        case basic = "Basic"
        case benefitAndReward = "BenefitAndReward"
        case creditInterest = "CreditInterest"
        case cashback = "Cashback"
        case general = "General"
        case graduate = "Graduate"
        case other = "Other"
        case overdraft = "Overdraft"
        case packaged = "Packaged"
        case premium = "Premium"
        case reward = "Reward"
        case student = "Student"
        case youngAdult = "YoungAdult"
        case youth = "Youth"
    }
    /** Market segmentation is a marketing term referring to the aggregating of prospective buyers into groups, or segments, that have common needs and respond similarly to a marketing action. Market segmentation enables companies to target different categories of consumers who perceive the full value of certain products and services differently from one another.  Read more: Market Segmentation http://www.investopedia.com/terms/m/marketsegmentation.asp#ixzz4gfEEalTd  With respect to PCA products, they are segmented in relation to different markets that they wish to focus on.  */
    public var segment: [Segment]?
    /** The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order */
    public var monthlyMaximumCharge: String?
    /** Optional additional notes to supplement the Core product details */
    public var notes: [String]?

    public init(segment: [Segment]?, monthlyMaximumCharge: String?, notes: [String]?) {
        self.segment = segment
        self.monthlyMaximumCharge = monthlyMaximumCharge
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey { 
        case segment = "Segment"
        case monthlyMaximumCharge = "MonthlyMaximumCharge"
        case notes = "Notes"
    }


}

