//
// Links.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Links relevant to the payload */

public struct Links: Codable {

    public var _self: String
    public var first: String?
    public var prev: String?
    public var next: String?
    public var last: String?

    public init(_self: String, first: String?, prev: String?, next: String?, last: String?) {
        self._self = _self
        self.first = first
        self.prev = prev
        self.next = next
        self.last = last
    }

    public enum CodingKeys: String, CodingKey { 
        case _self = "Self"
        case first = "First"
        case prev = "Prev"
        case next = "Next"
        case last = "Last"
    }


}

