//
// OBAddressTypeCode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Identifies the nature of the postal address. */
public enum OBAddressTypeCode: String, Codable {
    case business = "Business"
    case correspondence = "Correspondence"
    case deliveryTo = "DeliveryTo"
    case mailTo = "MailTo"
    case pobox = "POBox"
    case postal = "Postal"
    case residential = "Residential"
    case statement = "Statement"

}
