//
// OBBankTransactionCodeStructure1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to fully identify the type of underlying transaction resulting in an entry. */

public struct OBBankTransactionCodeStructure1: Codable {

    /** Specifies the family within a domain. */
    public var code: String
    /** Specifies the sub-product family within a specific family. */
    public var subCode: String

    public init(code: String, subCode: String) {
        self.code = code
        self.subCode = subCode
    }

    public enum CodingKeys: String, CodingKey { 
        case code = "Code"
        case subCode = "SubCode"
    }


}

