//
// OBExternalOfferType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Offer type, in a coded form. */
public enum OBExternalOfferType1Code: String, Codable {
    case balanceTransfer = "BalanceTransfer"
    case limitIncrease = "LimitIncrease"
    case moneyTransfer = "MoneyTransfer"
    case other = "Other"
    case promotionalRate = "PromotionalRate"

}
