//
// OBExternalLimitType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Limit type, in a coded form. */
public enum OBExternalLimitType1Code: String, Codable {
    case available = "Available"
    case credit = "Credit"
    case emergency = "Emergency"
    case preAgreed = "Pre-Agreed"
    case temporary = "Temporary"

}
