//
// OBExternalCardAuthorisationType1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The card authorisation type. */
public enum OBExternalCardAuthorisationType1Code: String, Codable {
    case consumerDevice = "ConsumerDevice"
    case contactless = "Contactless"
    case _none = "None"
    case pin = "PIN"

}
