//
// OBExternalDirectDebitStatus1Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the status of the direct debit in code form. */
public enum OBExternalDirectDebitStatus1Code: String, Codable {
    case active = "Active"
    case inactive = "Inactive"

}
