//
// OBMerchantDetails1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the merchant involved in the transaction. */

public struct OBMerchantDetails1: Codable {

    /** Name by which the merchant is known. */
    public var merchantName: String?
    /** Category code conform to ISO 18245, related to the type of services or goods the merchant provides for the transaction. */
    public var merchantCategoryCode: String?

    public init(merchantName: String?, merchantCategoryCode: String?) {
        self.merchantName = merchantName
        self.merchantCategoryCode = merchantCategoryCode
    }

    public enum CodingKeys: String, CodingKey { 
        case merchantName = "MerchantName"
        case merchantCategoryCode = "MerchantCategoryCode"
    }


}

