//
// OBReadScheduledPayment1Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadScheduledPayment1Data: Codable {

    public var scheduledPayment: [OBScheduledPayment1]?

    public init(scheduledPayment: [OBScheduledPayment1]?) {
        self.scheduledPayment = scheduledPayment
    }

    public enum CodingKeys: String, CodingKey { 
        case scheduledPayment = "ScheduledPayment"
    }


}

