//
// OBReadStandingOrder3Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OBReadStandingOrder3Data: Codable {

    public var standingOrder: [OBStandingOrder3]?

    public init(standingOrder: [OBStandingOrder3]?) {
        self.standingOrder = standingOrder
    }

    public enum CodingKeys: String, CodingKey { 
        case standingOrder = "StandingOrder"
    }


}

