//
// OBStatementRate1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Set of elements used to provide details of a generic rate related to the statement resource. */

public struct OBStatementRate1: Codable {

    /** Rate associated with the statement rate type. */
    public var rate: String
    /** Statement rate type, in a coded form. */
    public var type: String

    public init(rate: String, type: String) {
        self.rate = rate
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case rate = "Rate"
        case type = "Type"
    }


}

